In [2]:
import sqlite3
import pandas as pd
from tqdm import tqdm
import os

In [3]:
con = sqlite3.connect("vp_data2_isikud.db")
cur = con.cursor()
cur.execute('ATTACH DATABASE "v33.db" AS v33')

('ill', 'sisseütlev', 'illative'),

('in', 'seesütlev', 'inessive'),

('el', 'seestütlev', 'elative'),

('all', 'alaleütlev', 'allative'),

('ad', 'alalütlev', 'adessive'),

('abl', 'alaltütlev', 'ablative'),

## 1. tabel 
verb -> palju esineb obl+kääne (6 kohakäänet) : mitu matchi ja mitu distinct root 

 transactions_verbs_obl_kohakaandes_root_counts_distinct

 transactions_verbs_obl_kohakaandes_root_counts_distinct.csv

 transactions_verbs_obl_kohakaandes_root_counts_matches

 transactions_verbs_obl_kohakaandes_root_counts_matches.csv

In [3]:
query = """

SELECT *
from transactions_verbs_obl_kohakaandes_root_counts_distinct
"""

source = pd.read_sql_query(query, con)
source

,index,verb,abl_cnt,adit_cnt,all_cnt,ad_cnt,el_cnt,ill_cnt,in_cnt
0,0,toimuma,217,314,1026,2953,1076,164,6747
1,1,saama,5841,1510,6175,5967,21132,1263,9107
2,2,tulema,3199,2242,7121,9166,9139,2353,6342
3,3,viilima,2,0,3,16,29,1,14
4,4,muutuma,166,152,1180,1450,1288,121,2097
...,...,...,...,...,...,...,...,...,...
9613,9613,lastnuma,0,0,0,0,0,0,1
9614,9614,naajuma,0,0,0,0,0,0,1
9615,9615,sekskima,0,0,0,1,0,0,0
9616,9616,ampima,0,0,0,0,1,0,0
9617,9617,nexuma,0,0,0,1,0,0,1

## millised verbid + kääne on juba märgendatud ja millist on veel vaja

## lai tabel

In [5]:
# lahti pakitud märgenduste andmed
root = ".../margendatud"
margendused = pd.read_csv(os.path.join(root,"every_verb_case_obl.csv"), sep=";", encoding="utf-8")
margendused

,verbobl,verb,case,isikumäärus,aja-kohamäärus,muu
0,saama - abl (kellelt/millelt),saama,abl (kellelt/millelt),vahel,vahel,mitte kunagi
1,tulema - abl (kellelt/millelt),tulema,abl (kellelt/millelt),vahel,vahel,mitte kunagi
2,küsima - abl (kellelt/millelt),küsima,abl (kellelt/millelt),alati,mitte kunagi,mitte kunagi
3,nõudma - abl (kellelt/millelt),nõudma,abl (kellelt/millelt),alati,mitte kunagi,mitte kunagi
4,võtma - abl (kellelt/millelt),võtma,abl (kellelt/millelt),vahel,vahel,mitte kunagi
...,...,...,...,...,...,...
10574,musitseerima - in (kelles/milles),musitseerima,in (kelles/milles),mitte kunagi,alati,muu
10575,kõigutama - in (kelles/milles),kõigutama,in (kelles/milles),mitte kunagi,mitte kunagi,muu
10576,kätlema - in (kelles/milles),kätlema,in (kelles/milles),mitte kunagi,alati,muu
10577,kõmmutama - in (kelles/milles),kõmmutama,in (kelles/milles),mitte kunagi,alati,mitte kunagi
10578,sikutama - in (kelles/milles),sikutama,in (kelles/milles),mitte kunagi,alati,muu

In [6]:
paarid = []

for pair in list(margendused["verbobl"]):
    elems = pair.split("-")
    case = elems[1].split("(")[0].strip()
    verb = elems[0].split(" ")[0].strip()
    paarid.append((verb, case))

    
paarid = list(set(paarid))    
paarid

[('jälgima', 'in'),
 ('toimuma', 'el'),
 ('abielluma', 'all'),
 ('eeldama', 'in'),
 ('pidutsema', 'in'),
 ('tekitama', 'adit'),
 ('katma', 'ad'),
 ('raporteerima', 'el'),
 ('kehtestama', 'el'),
 ('kujunema', 'in'),
 ('peituma', 'ad'),
 ('marssima', 'in'),
 ('lõpma', 'ad'),
 ('leevendama', 'abl'),
 ('kuulduma', 'ad'),
 ('mekkima', 'all'),
 ('paiskuma', 'ad'),
 ('maanduma', 'adit'),
 ('kirjeldama', 'in'),
 ('utsitama', 'all'),
 ('roolima', 'all'),
 ('tervitama', 'abl'),
 ('julgema', 'adit'),
 ('sattuma', 'abl'),
 ('väisama', 'ad'),
 ('avama', 'abl'),
 ('etendama', 'ad'),
 ('trükkima', 'ad'),
 ('krabama', 'adit'),
 ('pumpama', 'ill'),
 ('välistama', 'ill'),
 ('käsitlema', 'el'),
 ('omama', 'ad'),
 ('lavastama', 'all'),
 ('paiknema', 'ad'),
 ('kohama', 'ad'),
 ('pasundama', 'ad'),
 ('kõrguma', 'all'),
 ('ilmnema', 'el'),
 ('pärima', 'abl'),
 ('keelduma', 'ill'),
 ('sätestama', 'ill'),
 ('hindama', 'ad'),
 ('harrastama', 'all'),
 ('võitlema', 'ad'),
 ('hävinema', 'ad'),
 ('sillutama', 'ad'),
 ('üllatama', 'ad'),
 ('pooldama', 'adit'),
 ('külvama', 'el'),
 ('lubama', 'ad'),
 ('äratama', 'abl'),
 ('elatuma', 'el'),
 ('proovima', 'all'),
 ('munema', 'ill'),
 ('väärima', 'el'),
 ('püstitama', 'in'),
 ('maksma', 'in'),
 ('hoolima', 'el'),
 ('vuhisema', 'all'),
 ('hõlmama', 'abl'),
 ('tundma', 'adit'),
 ('tarduma', 'in'),
 ('tungima', 'in'),
 ('kastma', 'all'),
 ('kargama', 'ill'),
 ('tirima', 'adit'),
 ('kõikuma', 'el'),
 ('koguma', 'all'),
 ('timmima', 'ad'),
 ('finisheerima', 'ad'),
 ('tunduma', 'all'),
 ('muretsema', 'el'),
 ('järgnema', 'in'),
 ('vajutama', 'ill'),
 ('osalema', 'ad'),
 ('tellima', 'all'),
 ('orienteeruma', 'in'),
 ('nihkuma', 'in'),
 ('alluma', 'all'),
 ('vedama', 'all'),
 ('punetama', 'in'),
 ('ründama', 'adit'),
 ('laskma', 'ill'),
 ('baseeruma', 'ad'),
 ('plaanitsema', 'all'),
 ('rakendama', 'ad'),
 ('ravima', 'in'),
 ('selguma', 'adit'),
 ('eraldama', 'ad'),
 ('lähetama', 'adit'),
 ('lugema', 'ill'),
 ('hüppama', 'abl'),
 ('uudistama', 'abl'),
 ('haistma', 'el'),
 ('pudistama', 'all'),
 ('vallutama', 'ad'),
 ('püüdma', 'el'),
 ('monteerima', 'ad'),
 ('vaidlustama', 'in'),
 ('tajuma', 'all'),
 ('ulatuma', 'adit'),
 ('ehitama', 'adit'),
 ('langema', 'all'),
 ('pakkima', 'all'),
 ('müütama', 'all'),
 ('paiskama', 'adit'),
 ('organiseerima', 'adit'),
 ('müüma', 'in'),
 ('kahetsema', 'all'),
 ('päästma', 'adit'),
 ('juhinduma', 'el'),
 ('omandama', 'in'),
 ('imponeerima', 'all'),
 ('tarnima', 'abl'),
 ('tekitama', 'ill'),
 ('seilama', 'ad'),
 ('ühtlustama', 'all'),
 ('lahustuma', 'ill'),
 ('ühinema', 'all'),
 ('määrima', 'adit'),
 ('riskeerima', 'ad'),
 ('põhinema', 'all'),
 ('pärlendama', 'el'),
 ('naeratama', 'in'),
 ('pikutama', 'ad'),
 ('laienema', 'ad'),
 ('lähtuma', 'adit'),
 ('imenduma', 'abl'),
 ('järgima', 'all'),
 ('käivitama', 'el'),
 ('tahtma', 'in'),
 ('vabanema', 'all'),
 ('julgema', 'ill'),
 ('kribima', 'all'),
 ('sisenema', 'abl'),
 ('kaitsma', 'el'),
 ('esilinastuma', 'in'),
 ('ilutsema', 'ad'),
 ('kubisema', 'all'),
 ('emiteerima', 'all'),
 ('mõtlema', 'abl'),
 ('soovima', 'all'),
 ('pikenema', 'abl'),
 ('vägistama', 'ad'),
 ('toituma', 'all'),
 ('tõusma', 'abl'),
 ('hõikama', 'el'),
 ('langetama', 'abl'),
 ('pooldama', 'ill'),
 ('haarama', 'adit'),
 ('jaotuma', 'all'),
 ('saalima', 'all'),
 ('jõustuma', 'ad'),
 ('paistma', 'all'),
 ('varitsema', 'in'),
 ('startima', 'ad'),
 ('eelnema', 'all'),
 ('tervitama', 'in'),
 ('alustama', 'ad'),
 ('taanduma', 'all'),
 ('lainetama', 'el'),
 ('sattuma', 'in'),
 ('hüplema', 'el'),
 ('täpsustuma', 'ad'),
 ('moodustama', 'ad'),
 ('avama', 'in'),
 ('suunama', 'ad'),
 ('eitama', 'in'),
 ('teenima', 'abl'),
 ('puhkema', 'el'),
 ('tundma', 'ill'),
 ('vahetama', 'adit'),
 ('funktsioneerima', 'ad'),
 ('registreeruma', 'abl'),
 ('etenduma', 'in'),
 ('üürima', 'adit'),
 ('edenema', 'adit'),
 ('tirima', 'ill'),
 ('otsustama', 'all'),
 ('pärima', 'in'),
 ('viitsima', 'ad'),
 ('asetsema', 'all'),
 ('nõudma', 'el'),
 ('nõutama', 'all'),
 ('silkama', 'ad'),
 ('äratama', 'in'),
 ('küsima', 'el'),
 ('asutama', 'abl'),
 ('tagastama', 'all'),
 ('triivima', 'abl'),
 ('teatama', 'ill'),
 ('passitama', 'all'),
 ('hõlmama', 'in'),
 ('vananema', 'all'),
 ('selguma', 'ill'),
 ('lähetama', 'ill'),
 ('sarnanema', 'all'),
 ('viitama', 'adit'),
 ('sodima', 'ad'),
 ('abistama', 'abl'),
 ('jaguma', 'adit'),
 ('tihendama', 'ad'),
 ('ulatuma', 'ill'),
 ('ehitama', 'ill'),
 ('väntama', 'adit'),
 ('avanema', 'ill'),
 ('lahustama', 'in'),
 ('sulama', 'ad'),
 ('seirama', 'abl'),
 ('paiskama', 'ill'),
 ('organiseerima', 'ill'),
 ('laitma', 'ad'),
 ('investeerima', 'all'),
 ('päästma', 'ill'),
 ('jagunema', 'abl'),
 ('vaikima', 'abl'),
 ('hüppama', 'in'),
 ('meenutama', 'ad'),
 ('visandama', 'el'),
 ('võõrandama', 'el'),
 ('häirima', 'abl'),
 ('vastutama', 'all'),
 ('elustama', 'ad'),
 ('kuhjama', 'ad'),
 ('tsiteerima', 'ad'),
 ('lähtuma', 'ill'),
 ('pussitama', 'in'),
 ('märgistama', 'all'),
 ('kannatama', 'el'),
 ('avaldama', 'all'),
 ('rüüpama', 'ad'),
 ('kippuma', 'all'),
 ('digima', 'all'),
 ('lahendama', 'adit'),
 ('pühitsema', 'all'),
 ('jöudnuma', 'all'),
 ('osutuma', 'abl'),
 ('toimetama', 'all'),
 ('puterdama', 'all'),
 ('valvama', 'in'),
 ('saavutama', 'el'),
 ('jätkama', 'el'),
 ('nuputama', 'all'),
 ('kimama', 'ill'),
 ('peitma', 'all'),
 ('mobiliseerima', 'in'),
 ('tänama', 'adit'),
 ('piirduma', 'ad'),
 ('tõmbuma', 'ad'),
 ('tooma', 'all'),
 ('raputama', 'abl'),
 ('tiirutama', 'all'),
 ('abielluma', 'abl'),
 ('upitama', 'all'),
 ('haarama', 'ill'),
 ('tappima', 'in'),
 ('osundama', 'all'),
 ('sisenema', 'in'),
 ('kohustuma', 'all'),
 ('kanduma', 'adit'),
 ('reageerima', 'adit'),
 ('teadma', 'el'),
 ('konkureerima', 'abl'),
 ('ootama', 'all'),
 ('vahetama', 'ill'),
 ('pummeldama', 'in'),
 ('ahenema', 'ad'),
 ('mõtlema', 'in'),
 ('alistuma', 'all'),
 ('üürima', 'ill'),
 ('värvuma', 'ad'),
 ('veenduma', 'ad'),
 ('tõusma', 'in'),
 ('langetama', 'in'),
 ('kulmineeruma', 'all'),
 ('pingutama', 'in'),
 ('pumpama', 'abl'),
 ('paeluma', 'adit'),
 ('välistama', 'abl'),
 ('rullima', 'all'),
 ('pankrotistuma', 'ad'),
 ('kõrvaldama', 'all'),
 ('põrkama', 'adit'),
 ('ühendama', 'ad'),
 ('keelduma', 'abl'),
 ('sätestama', 'abl'),
 ('vastandama', 'all'),
 ('teenima', 'in'),
 ('tuginema', 'all'),
 ('hõlbustama', 'el'),
 ('neelduma', 'ill'),
 ('kumama', 'ad'),
 ('viitama', 'ill'),
 ('tuletama', 'ill'),
 ('sadestuma', 'all'),
 ('pehmenema', 'ad'),
 ('jaguma', 'ill'),
 ('ärkama', 'all'),
 ('edendama', 'ad'),
 ('viibima', 'all'),
 ('väntama', 'ill'),
 ('manustama', 'el'),
 ('päädima', 'ad'),
 ('taguma', 'all'),
 ('asutama', 'in'),
 ('tuvastama', 'ad'),
 ('pilduma', 'adit'),
 ('loovutama', 'all'),
 ('sujuma', 'all'),
 ('kattuma', 'all'),
 ('töötama', 'adit'),
 ('lõhkema', 'ad'),
 ('mõjuma', 'adit'),
 ('kükitama', 'in'),
 ('pagema', 'ad'),
 ('katsetama', 'ad'),
 ('tutvustama', 'abl'),
 ('rahuldama', 'all'),
 ('kahtlustama', 'all'),
 ('uurima', 'ad'),
 ('paluma', 'el'),
 ('klikkama', 'all'),
 ('kaevama', 'all'),
 ('plaanima', 'all'),
 ('vajutama', 'abl'),
 ('distsiplineerima', 'ad'),
 ('fikseerima', 'all'),
 ('alanema', 'ad'),
 ('jaksama', 'all'),
 ('kõrvetama', 'all'),
 ('abistama', 'in'),
 ('ratifitseerima', 'all'),
 ('laskma', 'abl'),
 ('tõstma', 'all'),
 ('õnnestuma', 'el'),
 ('hakkama', 'adit'),
 ('kaardistama', 'all'),
 ('peksma', 'abl'),
 ('kõõluma', 'in'),
 ('rääkima', 'el'),
 ('kraapima', 'abl'),
 ('kvalifitseeruma', 'ad'),
 ('ära', 'all'),
 ('röövima', 'el'),
 ('jagunema', 'in'),
 ('iseseisvuma', 'all'),
 ('kukkuma', 'adit'),
 ('kärisema', 'ad'),
 ('tugevdama', 'in'),
 ('lõpetama', 'all'),
 ('keelama', 'el'),
 ('luhtuma', 'el'),
 ('kujutama', 'ad'),
 ('tänama', 'ill'),
 ('eristama', 'all'),
 ('sisalduma', 'all'),
 ('saatma', 'ad'),
 ('sobima', 'el'),
 ('pantima', 'all'),
 ('määrduma', 'ad'),
 ('kahetsema', 'abl'),
 ('punnitama', 'ad'),
 ('linastuma', 'abl'),
 ('hävitama', 'el'),
 ('hävima', 'adit'),
 ('käristama', 'all'),
 ('tormama', 'el'),
 ('sisustama', 'all'),
 ('tihenema', 'all'),
 ('sirguma', 'abl'),
 ('taandama', 'abl'),
 ('kihutama', 'adit'),
 ('erinema', 'adit'),
 ('tükkima', 'all'),
 ('suruma', 'el'),
 ('osutuma', 'in'),
 ('kandideerima', 'all'),
 ('kohmama', 'all'),
 ('balansseerima', 'ad'),
 ('ärritama', 'all'),
 ('kiitma', 'abl'),
 ('kärbuma', 'ad'),
 ('ütlema', 'el'),
 ('kasvatama', 'all'),
 ('kivistuma', 'ill'),
 ('hiilima', 'all'),
 ('testima', 'ad'),
 ('voolima', 'ad'),
 ('maanduma', 'abl'),
 ('värisema', 'ad'),
 ('finantseerima', 'abl'),
 ('raputama', 'in'),
 ('julgema', 'abl'),
 ('broneerima', 'ad'),
 ('puiklema', 'all'),
 ('krabama', 'abl'),
 ('imema', 'all'),
 ('norima', 'abl'),
 ('vaevuma', 'all'),
 ('kiskuma', 'el'),
 ('vilgutama', 'all'),
 ('paigaldama', 'adit'),
 ('domineerima', 'abl'),
 ('võlgnema', 'all'),
 ('painama', 'ad'),
 ('passima', 'ad'),
 ('aitama', 'el'),
 ('põrkama', 'ill'),
 ('õnnitlema', 'all'),
 ('projekteerima', 'all'),
 ('kallutama', 'all'),
 ('süütama', 'all'),
 ('pooldama', 'abl'),
 ('tegelema', 'adit'),
 ('konkureerima', 'in'),
 ('kompenseerima', 'abl'),
 ('esindama', 'el'),
 ('parafeerima', 'ad'),
 ('taanduma', 'abl'),
 ('produtseerima', 'all'),
 ('hääletama', 'el'),
 ('minestama', 'ad'),
 ('ehtima', 'ad'),
 ('torkama', 'all'),
 ('hoiduma', 'el'),
 ('turustama', 'el'),
 ('võõrustama', 'el'),
 ('alistama', 'all'),
 ('pumpama', 'in'),
 ('läkitama', 'abl'),
 ('kinkima', 'ad'),
 ('välistama', 'in'),
 ('tundma', 'abl'),
 ('kloppima', 'abl'),
 ('vähkrema', 'ad'),
 ('pilduma', 'ill'),
 ('lasuma', 'all'),
 ('keelduma', 'in'),
 ('sätestama', 'in'),
 ('töötama', 'ill'),
 ('mõjuma', 'ill'),
 ('kaugenema', 'all'),
 ('mõlkuma', 'ad'),
 ('võistlema', 'all'),
 ('vähenema', 'all'),
 ('sallima', 'ad'),
 ('piitsutama', 'ad'),
 ('munema', 'in'),
 ('nutma', 'in'),
 ('küündima', 'adit'),
 ('küpsetama', 'el'),
 ('kujundama', 'abl'),
 ('koostama', 'all'),
 ('jamama', 'all'),
 ('viljelema', 'ad'),
 ('ründama', 'abl'),
 ('istutama', 'all'),
 ('liuglema', 'ill'),
 ('teatama', 'abl'),
 ('triikima', 'all'),
 ('asendama', 'in'),
 ('selguma', 'abl'),
 ('taotlema', 'all'),
 ('piinama', 'all'),
 ('pälvima', 'el'),
 ('hakkama', 'ill'),
 ('muutuma', 'ill'),
 ('siginema', 'el'),
 ('vältima', 'adit'),
 ('murduma', 'el'),
 ('kukkuma', 'ill'),
 ('tutvustama', 'in'),
 ('sagenema', 'ad'),
 ('punuma', 'all'),
 ('hoomama', 'ad'),
 ('märkima', 'all'),
 ('vajutama', 'in'),
 ('sikutama', 'el'),
 ('tunnistama', 'ad'),
 ('paiskama', 'abl'),
 ('organiseerima', 'abl'),
 ('päästma', 'abl'),
 ('näitama', 'abl'),
 ('seadma', 'all'),
 ('laskma', 'in'),
 ('kavatsema', 'abl'),
 ('kihutama', 'ill'),
 ('kustuma', 'ad'),
 ('edestama', 'all'),
 ('määrima', 'abl'),
 ('lugema', 'in'),
 ('peksma', 'in'),
 ('hoidma', 'adit'),
 ('eskortima', 'ad'),
 ('loksuma', 'ill'),
 ('putkama', 'ill'),
 ('tuhisema', 'ad'),
 ('pöörama', 'el'),
 ('tarbima', 'abl'),
 ('installeerima', 'all'),
 ('võrsuma', 'el'),
 ('sülitama', 'ill'),
 ('alandama', 'ad'),
 ('iseloomustama', 'ad'),
 ('kõlbama', 'adit'),
 ('linastuma', 'in'),
 ('kituma', 'all'),
 ('sirguma', 'in'),
 ('ergutama', 'all'),
 ('paigaldama', 'ill'),
 ('nihutama', 'abl'),
 ('helendama', 'all'),
 ('panema', 'ad'),
 ('himustama', 'all'),
 ('kuulutama', 'ad'),
 ('lahustuma', 'in'),
 ('soetama', 'adit'),
 ('mängima', 'all'),
 ('toksima', 'ill'),
 ('paigutama', 'all'),
 ('tootma', 'all'),
 ('esitlema', 'el'),
 ('tegelema', 'ill'),
 ('kiitma', 'in'),
 ('haarama', 'abl'),
 ('kirjutama', 'abl'),
 ('seisma', 'el'),
 ('suvitama', 'ad'),
 ('anduma', 'ad'),
 ('maanduma', 'in'),
 ('puutuma', 'adit'),
 ('tunnustama', 'adit'),
 ('lausuma', 'all'),
 ('julgema', 'in'),
 ('katkema', 'all'),
 ('meelitama', 'adit'),
 ('önnestuma', 'ad'),
 ('käituma', 'el'),
 ('tõstatama', 'abl'),
 ('domineerima', 'in'),
 ('pettuma', 'in'),
 ('täpsustama', 'ad'),
 ('vahetama', 'abl'),
 ('teenindama', 'ad'),
 ('sosistama', 'abl'),
 ('suunduma', 'ad'),
 ('puhastama', 'all'),
 ('koormama', 'all'),
 ('tingima', 'ad'),
 ('pooldama', 'in'),
 ('lööma', 'all'),
 ('rippuma', 'el'),
 ('kuulatama', 'ad'),
 ('arvama', 'all'),
 ('puhuma', 'ad'),
 ('seostuma', 'adit'),
 ('küündima', 'ill'),
 ('hüüatama', 'all'),
 ('põlema', 'all'),
 ('prantsatama', 'adit'),
 ('rüütama', 'ill'),
 ('tipnema', 'in'),
 ('mõjutama', 'ad'),
 ('rajama', 'ad'),
 ('lisama', 'el'),
 ('loosima', 'all'),
 ('tundma', 'in'),
 ('jagama', 'ad'),
 ('vältima', 'ill'),
 ('lahkuma', 'ad'),
 ('pusima', 'ad'),
 ('viitama', 'abl'),
 ('piisama', 'el'),
 ('keema', 'in'),
 ('lahvatama', 'ad'),
 ('varjama', 'abl'),
 ('looma', 'el'),
 ('nakatama', 'all'),
 ('jaguma', 'abl'),
 ('juhtuma', 'all'),
 ('rügama', 'ad'),
 ('kajastuma', 'all'),
 ('kütma', 'ad'),
 ('pakkuma', 'abl'),
 ('kindlustama', 'abl'),
 ('kujundama', 'in'),
 ('päevitama', 'ad'),
 ('katma', 'all'),
 ('ründama', 'in'),
 ('läbima', 'all'),
 ('kruvima', 'abl'),
 ('teatama', 'in'),
 ('rabama', 'ad'),
 ('peituma', 'all'),
 ('selguma', 'in'),
 ('võluma', 'all'),
 ('patrullima', 'in'),
 ('hämmelduma', 'el'),
 ('eksportima', 'ad'),
 ('hoidma', 'ill'),
 ('lõpma', 'all'),
 ('laienema', 'adit'),
 ('heitma', 'ad'),
 ('kündma', 'ad'),
 ('jaksama', 'abl'),
 ('vaevama', 'all'),
 ('põhjendama', 'ill'),
 ('paiskuma', 'all'),
 ('murdma', 'abl'),
 ('õigustama', 'abl'),
 ('keelitama', 'all'),
 ('lehvima', 'in'),
 ('räppima', 'all'),
 ('edastama', 'el'),
 ('paiskama', 'in'),
 ('organiseerima', 'in'),
 ('jutustama', 'all'),
 ('kõlbama', 'ill'),
 ('väisama', 'all'),
 ('päästma', 'in'),
 ('etendama', 'all'),
 ('rikastuma', 'ad'),
 ('trükkima', 'all'),
 ('näitama', 'in'),
 ('kavatsema', 'in'),
 ('omama', 'all'),
 ('paiknema', 'all'),
 ('kohama', 'all'),
 ('kiirgama', 'all'),
 ('läxima', 'all'),
 ('korjama', 'adit'),
 ('soetama', 'ill'),
 ('tänama', 'abl'),
 ('hõõruma', 'adit'),
 ('pärssima', 'ad'),
 ('toetama', 'el'),
 ('astuma', 'adit'),
 ('võitlema', 'all'),
 ('hävinema', 'all'),
 ('liigitama', 'all'),
 ('ühtima', 'ad'),
 ('üllatama', 'all'),
 ('suhtuma', 'el'),
 ('tarbima', 'in'),
 ('kogunema', 'adit'),
 ('puutuma', 'ill'),
 ('aretama', 'all'),
 ('vupsama', 'el'),
 ('kiirustama', 'ad'),
 ('harima', 'ad'),
 ('imama', 'all'),
 ('meelitama', 'ill'),
 ('rüselema', 'ad'),
 ('kanduma', 'abl'),
 ('tulvama', 'el'),
 ('reageerima', 'abl'),
 ('kobima', 'all'),
 ('kuhjuma', 'ad'),
 ('hammustama', 'all'),
 ('sammuma', 'ad'),
 ('venima', 'el'),
 ('kõigutama', 'ill'),
 ('keerama', 'el'),
 ('nullima', 'all'),
 ('annetama', 'all'),
 ('filosofeerima', 'ad'),
 ('juhatama', 'el'),
 ('haarama', 'in'),
 ('diagnoosima', 'el'),
 ('kirjutama', 'in'),
 ('unistama', 'adit'),
 ('vaatama', 'adit'),
 ('kobama', 'abl'),
 ('minema', 'el'),
 ('tõttama', 'abl'),
 ('põrkama', 'abl'),
 ('prantsatama', 'ill'),
 ('baseeruma', 'all'),
 ('rakendama', 'all'),
 ('vallanduma', 'ad'),
 ('tõstatama', 'in'),
 ('maabuma', 'all'),
 ('vahetama', 'in'),
 ('edenema', 'in'),
 ('jalutama', 'ad'),
 ('vallutama', 'all'),
 ('üritama', 'el'),
 ('rajanema', 'ad'),
 ('monteerima', 'all'),
 ('protestima', 'all'),
 ('levima', 'adit'),
 ('avalikustama', 'ad'),
 ('tantsima', 'adit'),
 ('häälitsema', 'ad'),
 ('importima', 'all'),
 ('pilduma', 'abl'),
 ('seilama', 'all'),
 ('suurendama', 'adit'),
 ('tunglema', 'in'),
 ('mõjuma', 'abl'),
 ('potsatama', 'adit'),
 ('paranema', 'all'),
 ('vahendama', 'ad'),
 ('keskenduma', 'ad'),
 ('jutlustama', 'el'),
 ('tõotama', 'ill'),
 ('hääbuma', 'adit'),
 ('kupatama', 'adit'),
 ('lükkama', 'el'),
 ('dirigeerima', 'el'),
 ('sisendama', 'adit'),
 ('murenema', 'ad'),
 ('andma', 'adit'),
 ('viitama', 'in'),
 ('kuhjama', 'adit'),
 ('soojendama', 'all'),
 ('varjama', 'in'),
 ('jaguma', 'in'),
 ('sajatama', 'ad'),
 ('rüüpama', 'adit'),
 ('debüteerima', 'ad'),
 ('seiskuma', 'ad'),
 ('lõhkuma', 'abl'),
 ('ruttama', 'all'),
 ('pakkuma', 'in'),
 ('kindlustama', 'in'),
 ('laulma', 'all'),
 ('oletama', 'all'),
 ('piirama', 'all'),
 ('ilutsema', 'all'),
 ('kukkuma', 'abl'),
 ('külmuma', 'ad'),
 ('purustama', 'adit'),
 ('heietama', 'all'),
 ('korjama', 'ill'),
 ('hajuma', 'el'),
 ('hõõruma', 'ill'),
 ('astuma', 'ill'),
 ('riskima', 'abl'),
 ('huvitama', 'ad'),
 ('kleepima', 'all'),
 ('musitseerima', 'in'),
 ('ihaldama', 'ad'),
 ('jõustuma', 'all'),
 ('sisaldama', 'all'),
 ('võrdlema', 'all'),
 ('sopsama', 'abl'),
 ('kogunema', 'ill'),
 ('tunnetama', 'adit'),
 ('tasakaalustama', 'all'),
 ('murdma', 'in'),
 ('kohtuma', 'all'),
 ('õigustama', 'in'),
 ('alustama', 'all'),
 ('kaunistama', 'adit'),
 ('liputama', 'all'),
 ('rühkima', 'abl'),
 ('vorpima', 'all'),
 ('illustreerima', 'ad'),
 ('käivituma', 'el'),
 ('täpsustuma', 'all'),
 ('erinema', 'abl'),
 ('nimetama', 'adit'),
 ('suunama', 'all'),
 ('naerma', 'ad'),
 ('filmima', 'abl'),
 ('kartma', 'el'),
 ('vastama', 'all'),
 ('allutama', 'ad'),
 ('eksima', 'el'),
 ('sahisema', 'ad'),
 ('mahtuma', 'ad'),
 ('tänama', 'in'),
 ('külastama', 'adit'),
 ('viitsima', 'all'),
 ('pugema', 'adit'),
 ('vuristama', 'ad'),
 ('suhtlema', 'el'),
 ('platseeruma', 'el'),
 ('unistama', 'ill'),
 ('kuuluma', 'adit'),
 ('paigaldama', 'abl'),
 ('vaatama', 'ill'),
 ('oskama', 'abl'),
 ('realiseerima', 'in'),
 ('irduma', 'abl'),
 ('reageerima', 'in'),
 ('julgustama', 'ill'),
 ('veetma', 'el'),
 ('sooritama', 'el'),
 ('sumpama', 'ad'),
 ('särama', 'adit'),
 ('käima', 'el'),
 ('rentima', 'all'),
 ('plahvatama', 'ad'),
 ('liibuma', 'all'),
 ('soojenema', 'all'),
 ('õpetama', 'el'),
 ('hankima', 'el'),
 ('levima', 'ill'),
 ('heitlema', 'in'),
 ('jahvatama', 'all'),
 ('lähenema', 'abl'),
 ('vilksatama', 'ad'),
 ('katkestama', 'adit'),
 ('nentima', 'el'),
 ('valmistama', 'ad'),
 ('tantsima', 'ill'),
 ('sulama', 'all'),
 ('aktiveerima', 'ad'),
 ('näima', 'all'),
 ('demonstreerima', 'ad'),
 ('kroolima', 'all'),
 ('helistama', 'ad'),
 ('tuuritama', 'ad'),
 ('põrkama', 'in'),
 ('viskama', 'ad'),
 ('suurendama', 'ill'),
 ('potsatama', 'ill'),
 ('rändama', 'ad'),
 ('kergitama', 'ad'),
 ('hääbuma', 'ill'),
 ('kupatama', 'ill'),
 ('tõestama', 'adit'),
 ('sisendama', 'ill'),
 ('märkama', 'all'),
 ('andma', 'ill'),
 ('võitma', 'all'),
 ('küündima', 'abl'),
 ('valmima', 'all'),
 ('segama', 'el'),
 ('tähendama', 'ad'),
 ('märatsema', 'ad'),
 ('võrdsustama', 'ad'),
 ('eemaldama', 'all'),
 ('käärima', 'el'),
 ('pragunema', 'ad'),
 ('hilinema', 'all'),
 ('viima', 'ad'),
 ('kehtestuma', 'all'),
 ('askeldama', 'ad'),
 ('mõjuma', 'in'),
 ('muutma', 'el'),
 ('deklareerima', 'abl'),
 ('piirduma', 'all'),
 ('tõhustama', 'ad'),
 ('nõustuma', 'el'),
 ('noogutama', 'abl'),
 ('kantima', 'all'),
 ('pommitama', 'all'),
 ('igatsema', 'adit'),
 ('pelgama', 'adit'),
 ('suutma', 'ad'),
 ('perima', 'all'),
 ('putitama', 'ad'),
 ('vudima', 'all'),
 ('talletuma', 'ill'),
 ('karjuma', 'ill'),
 ('kutsuma', 'all'),
 ('peatama', 'ad'),
 ('põrutama', 'ad'),
 ('väitma', 'ad'),
 ('lõhkuma', 'in'),
 ('tegutsema', 'adit'),
 ('lippama', 'abl'),
 ('nimetama', 'ill'),
 ('lajatama', 'ad'),
 ('kukkuma', 'in'),
 ('kuulduma', 'abl'),
 ('muhelema', 'ad'),
 ('seljatama', 'all'),
 ('kostma', 'ad'),
 ('ahenema', 'all'),
 ('viirastuma', 'ad'),
 ('ammutama', 'ad'),
 ('ristlema', 'in'),
 ('hukkuma', 'ad'),
 ('veenduma', 'all'),
 ('külastama', 'ill'),
 ('õhkuma', 'ad'),
 ('sõitma', 'el'),
 ('pugema', 'ill'),
 ('postitama', 'all'),
 ('kõlbama', 'abl'),
 ('puuduma', 'ad'),
 ('kuduma', 'ad'),
 ('pigistama', 'adit'),
 ('kuuluma', 'ill'),
 ('sulatama', 'ill'),
 ('kosuma', 'all'),
 ('reklaamima', 'all'),
 ('shokeerima', 'ad'),
 ('ühendama', 'all'),
 ('erinema', 'in'),
 ('ennustama', 'adit'),
 ('hindama', 'abl'),
 ('üllatama', 'abl'),
 ('torkima', 'adit'),
 ('loksuma', 'in'),
 ('küllastuma', 'ad'),
 ('võrduma', 'el'),
 ('valmistuma', 'ad'),
 ('lubama', 'abl'),
 ('purunema', 'ad'),
 ('järelduma', 'abl'),
 ('ümbritsema', 'adit'),
 ('keerlema', 'ad'),
 ('figureerima', 'in'),
 ('diskuteerima', 'ad'),
 ('väljendama', 'adit'),
 ('nördima', 'el'),
 ('meelitama', 'abl'),
 ('elama', 'adit'),
 ('katkestama', 'ill'),
 ('joonistama', 'adit'),
 ('põristama', 'all'),
 ('tuvastama', 'all'),
 ('oskama', 'in'),
 ('riknema', 'ad'),
 ('menetlema', 'all'),
 ('väsima', 'ad'),
 ('deponeerima', 'all'),
 ('säilima', 'el'),
 ('varisema', 'adit'),
 ('peegeldama', 'all'),
 ('kerjama', 'abl'),
 ('katsetama', 'all'),

In [52]:
source2 = pd.read_sql_query(query, con)

In [53]:
source2 = source2.drop(["index"], axis=1)

In [54]:
source2["annotated"] = None

In [57]:
source2["num_cover"] = 0

In [58]:
source2

,verb,abl_cnt,adit_cnt,all_cnt,ad_cnt,el_cnt,ill_cnt,in_cnt,annotated,num_cover
0,toimuma,217,314,1026,2953,1076,164,6747,None,0
1,saama,5841,1510,6175,5967,21132,1263,9107,None,0
2,tulema,3199,2242,7121,9166,9139,2353,6342,None,0
3,viilima,2,0,3,16,29,1,14,None,0
4,muutuma,166,152,1180,1450,1288,121,2097,None,0
...,...,...,...,...,...,...,...,...,...,...
9613,lastnuma,0,0,0,0,0,0,1,None,0
9614,naajuma,0,0,0,0,0,0,1,None,0
9615,sekskima,0,0,0,1,0,0,0,None,0
9616,ampima,0,0,0,0,1,0,0,None,0
9617,nexuma,0,0,0,1,0,0,1,None,0

In [7]:
ann_dict1 = {}

for e in tqdm(paarid):
    verb = e[0]
    case = e[1]
    if verb in ann_dict1.keys():
        ann_dict1[verb].append(case)
    else:
        ann_dict1[verb] = [case]
        

ann_dict =  {}
for k in ann_dict1.keys():
    l = sorted(ann_dict1[k])
    ann_dict[k] = l
    
ann_dict2 =  {}
for k in ann_dict.keys():
    l = ",".join(ann_dict[k])
    num = len(ann_dict[k])
    ann_dict2[k] = (l,num)

100%|██████████████████████████████████| 7248/7248 [00:00<00:00, 1489700.37it/s]

In [61]:
for i in range(len(source2)):
    verb = source2.iloc[i]["verb"]
    if verb in ann_dict2.keys():
        source2.at[i, "annotated"] = ann_dict2[verb][0]
        source2.at[i, "num_cover"] = ann_dict2[verb][1]

In [62]:
source2

,verb,abl_cnt,adit_cnt,all_cnt,ad_cnt,el_cnt,ill_cnt,in_cnt,annotated,num_cover
0,toimuma,217,314,1026,2953,1076,164,6747,"abl,ad,adit,all,el,ill,in",7
1,saama,5841,1510,6175,5967,21132,1263,9107,"abl,ad,adit,all,el,ill,in",7
2,tulema,3199,2242,7121,9166,9139,2353,6342,"abl,ad,adit,all,el,ill,in",7
3,viilima,2,0,3,16,29,1,14,None,0
4,muutuma,166,152,1180,1450,1288,121,2097,"abl,ad,adit,all,el,ill,in",7
...,...,...,...,...,...,...,...,...,...,...
9613,lastnuma,0,0,0,0,0,0,1,None,0
9614,naajuma,0,0,0,0,0,0,1,None,0
9615,sekskima,0,0,0,1,0,0,0,None,0
9616,ampima,0,0,0,0,1,0,0,None,0
9617,nexuma,0,0,0,1,0,0,1,None,0

In [63]:
source2.to_csv("transactions_verbs_obl_kohakaandes_root_counts_distinct_coverage.csv", encoding="utf-8", index=False, sep=";")

In [64]:
source2.to_sql(name='transactions_verbs_obl_kohakaandes_root_counts_distinct_coverage', con=con)

9618

## sisuliselt sama asi aga kitsas tabel

In [9]:
q = """
SELECT 
    distinct verb, 
    kaane, 
    count(distinct root_word) as root_count,
    'false' as annotated

FROM transactions_verbs_obl_kohakaandes
group by verb, kaane
order by root_count desc
"""

s3 = pd.read_sql_query(q, con)
s3

                 verb kaane  root_count annotated
0               saama    el       21132     false
1               andma   all       12526     false
2             rääkima    el       10930     false
3               jääma    el        9936     false
4              tulema    ad        9166     false
...               ...   ...         ...       ...
30081       šveitsima    el           1     false
30082        švipsima    ad           1     false
30083  žestikuleerima    ad           1     false
30084      žisraelima    ad           1     false
30085       хnnestuma    in           1     false

[30086 rows x 4 columns]

In [11]:
for i in tqdm(range(len(s3))):
    v_k = (s3.iloc[i]["verb"],s3.iloc[i]["kaane"])
    if v_k in paarid:
        s3.at[i, "annotated"] ='true'

100%|███████████████████████████████████| 30086/30086 [00:06<00:00, 4342.90it/s]

In [12]:
s3

                 verb kaane  root_count annotated
0               saama    el       21132      true
1               andma   all       12526      true
2             rääkima    el       10930      true
3               jääma    el        9936      true
4              tulema    ad        9166      true
...               ...   ...         ...       ...
30081       šveitsima    el           1     false
30082        švipsima    ad           1     false
30083  žestikuleerima    ad           1     false
30084      žisraelima    ad           1     false
30085       хnnestuma    in           1     false

[30086 rows x 4 columns]

In [13]:
s3.to_csv("transactions_verbs_obl_kohakaandes_root_counts_distinct_coverage_v2.csv", encoding="utf-8", index=False, sep=";")

In [15]:
s3[(s3["annotated"]=='false') & (s3["root_count"]>=100)]

          verb kaane  root_count annotated
1564   tõmbuma    el         238     false
1776   hiilima    el         202     false
1813   kargama    el         197     false
1962    pistma    el         178     false
2174  pressima    el         155     false
...        ...   ...         ...       ...
2966     petma    in         101     false
2970   trügima    in         101     false
2977   kaevama    el         100     false
2980  kukutama    in         100     false
2985   rühkima    in         100     false

[64 rows x 4 columns]

In [ ]:
###################################################################################################################
###################################################################################################################

## 2. tabel

iga verb+obl+kohakääne jaoks count elus ja count koht, count kokku

 transactions_verbs_obl_kohakaandes_eluskoht_root_counts_distinct
 
 transactions_verbs_obl_kohakaandes_eluskoht_root_counts_matches

In [4]:
query = """

SELECT *
from transactions_verbs_obl_kohakaandes_eluskoht_root_counts_distinct
"""

source = pd.read_sql_query(query, con)
source

,index,verb,kaane,verb_kaane,elus_cnt,koht_cnt,root_cnt
0,0,saama,el,saama_el,1317,408,21132
1,1,andma,all,andma_all,1649,267,12526
2,2,rääkima,el,rääkima_el,805,202,10930
3,3,jääma,el,jääma_el,709,265,9936
4,4,tulema,ad,tulema_ad,1178,174,9166
...,...,...,...,...,...,...,...
30081,30081,šveitsima,el,šveitsima_el,0,0,1
30082,30082,švipsima,ad,švipsima_ad,0,0,1
30083,30083,žestikuleerima,ad,žestikuleerima_ad,0,1,1
30084,30084,žisraelima,ad,žisraelima_ad,0,0,1
30085,30085,хnnestuma,in,хnnestuma_in,0,0,1

## elus vs koht

In [15]:
query = """

SELECT *
from transactions_verbs_obl_kohakaandes_eluskoht_root_counts_distinct
where elus_cnt > koht_cnt
and elus_cnt >= 3*koht_cnt
order by elus_cnt desc
limit 500
"""

source = pd.read_sql_query(query, con)
source

     index          verb kaane        verb_kaane  elus_cnt  koht_cnt  root_cnt
0        1         andma   all         andma_all      1649       267     12526
1        0         saama    el          saama_el      1317       408     21132
2        4        tulema    ad         tulema_ad      1178       174      9166
3       10        tegema   all        tegema_all      1169       224      7684
4        7         jääma   all         jääma_all      1065       228      8365
..     ...           ...   ...               ...       ...       ...       ...
495   3004  kritiseerima    el   kritiseerima_el        25         5        98
496   3133  avalikustama   all  avalikustama_all        25         4        92
497   3156       passima   all       passima_all        25         5        91
498   3231    reageerima    el     reageerima_el        25         4        88
499   3354        armuma  adit       armuma_adit        25         6        82

[500 rows x 7 columns]

In [9]:
query = """

SELECT *
from transactions_verbs_obl_kohakaandes_eluskoht_root_counts_distinct
where koht_cnt > elus_cnt
order by koht_cnt desc
limit 500
"""

source2 = pd.read_sql_query(query, con)
source2

     index       verb kaane     verb_kaane  elus_cnt  koht_cnt  root_cnt
0       11      käima    in       käima_in       102       360      7151
1       32      elama    in       elama_in       110       337      4824
2       13    toimuma    in     toimuma_in        86       333      6747
3        6      saama    in       saama_in       139       326      9107
4       45      asuma    in       asuma_in        49       325      4200
..     ...        ...   ...            ...       ...       ...       ...
495   1485    rändama    el     rändama_el        10        38       253
496   1551     lamama    ad      lamama_ad         9        38       240
497   1581  paigutama   all  paigutama_all         8        38       235
498   1780   laiutama    in    laiutama_in         7        38       202
499   1827  meelitama   ill  meelitama_ill         7        38       195

[500 rows x 7 columns]

In [14]:
# koht

query = """

SELECT *
from transactions_verbs_obl_kohakaandes_eluskoht_root_counts_distinct
where koht_cnt > elus_cnt
and koht_cnt >= 3*elus_cnt
order by koht_cnt desc
limit 500
"""

source2 = pd.read_sql_query(query, con)
source2

     index        verb kaane      verb_kaane  elus_cnt  koht_cnt  root_cnt
0       11       käima    in        käima_in       102       360      7151
1       32       elama    in        elama_in       110       337      4824
2       13     toimuma    in      toimuma_in        86       333      6747
3       45       asuma    in        asuma_in        49       325      4200
4       26     töötama    in      töötama_in        67       222      5170
..     ...         ...   ...             ...       ...       ...       ...
495   2677      laiuma    ad       laiuma_ad         2        22       116
496   2688    sagenema    in     sagenema_in         3        22       116
497   2794  opereerima    in   opereerima_in         1        22       110
498   3090      uitama    in       uitama_in         4        22        95
499   3418   sõidutama  adit  sõidutama_adit         4        22        80

[500 rows x 7 columns]

In [16]:
con.close()