## GPT n20 v01 gpt b10 run01 analysis

### requires python >= 3.10

In [1]:
import sqlite3
import pandas as pd
from tqdm import tqdm
import numpy as np
import copy
import os
import configparser
import json
import time
import csv

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option("display.show_dimensions", True)

In [3]:
DATA_FILE = "../../results/n50_examples_large_v01/gpt_v02/gpt_b10_run01.csv"

## Vastustega df

In [4]:
df1 = pd.read_csv(DATA_FILE, encoding="utf-8", sep=",")

In [5]:
len(df1[df1["classification"]=="yes"]) # koht

6336

In [6]:
len(df1[df1["classification"]=="no"]) # mitte koht

3664

In [12]:
# iga prompt jooksutada eelneva prompti "no" peal
(600701 + 345468 + 242119 + 286686 + 213534)/1000000*2.14

3.61340712

In [14]:
600701*5

3003505

In [17]:
# kui timex, alive, event ja org jooksutada kohu loc=no peal
(600701*4)/1000000*2.14

5.1420005600000005

In [19]:
# timex ja alive jooksutada kogu loc=no peal
(412063 + 396263 + 464932)/1000000*2.14

2.7247721200000004

### kas saab olla aeg ja tegija samal ajal

In [22]:
df1[(df1["is_time"]=="yes") & (df1["is_alive"]=="yes")]

Empty DataFrame
Columns: [sentence_id, head_id, head_loc, verb, verb_compound, morph_case, lemma, form, sentence, timex_tag, ekilex_tag, ner_tag, classification, explanation, is_time, is_alive, is_event, is_org, is_abstract, classification2]
Index: []

[0 rows x 20 columns]

In [23]:
df1[(df1["is_time"]=="yes") & (df1["is_org"]=="yes")]

Empty DataFrame
Columns: [sentence_id, head_id, head_loc, verb, verb_compound, morph_case, lemma, form, sentence, timex_tag, ekilex_tag, ner_tag, classification, explanation, is_time, is_alive, is_event, is_org, is_abstract, classification2]
Index: []

[0 rows x 20 columns]

### kas abstract koht saab olla aeg

In [7]:
df1[(df1["is_abstract"]=="yes") & (df1["is_time"]=="yes")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
105,18849565,28466497,21,kajastuma,NaN,in,eelmine,eelmistes,"Me hääletasime ainult ühe korra , mis aga praegustes muudatusettepanekutes ei kajastu , sest see kajastus minu mälestust mööda juba eelmistes .",NaN,NaN,NaN,no,"The phrase 'eelmistes' refers to previous proposals or contexts and does not describe a location, hence it is not adverbial of place.",yes,no,no,no,yes,loc
202,6783830,10913630,13,sõitma,NaN,in,augustipimedus,augustipimeduses,"Olen selle kohaga nii kokku kasvanud , et kui ma näiteks siin augustipimeduses rattaga sõidan , tean kõiki teepealseid juurikaid peast .",NaN,NaN,NaN,no,"The phrase 'augustipimeduses' refers to a time period rather than a location, so it is not an adverbial of place.",yes,no,no,no,yes,loc
204,4526783,7276665,5,ristuma,NaN,in,avavoor,avavoorus,"Dortmundi Borussia tee ristub avavoorus laupäeval võõral väljakul Leverkuseni Bayeriga , Müncheni Bayern kohtub reedel ühe autsaideri St.",NaN,event,NaN,no,"The phrase 'avavoorus' refers to an event or time frame, not to a location, hence it is not an adverbial of place.",yes,no,no,no,yes,loc
208,16105875,25002385,11,vabastama,NaN,in,voor,voorus,""" Ashkelon vabastas Babenko pärast tema viletsaid esitusi esimeses neljas voorus , kus ta viskas keskmiselt 3 punkti , "" teatas Iisraeli korvpallianalüütik Shlomi Peri Sõnumilehele .",NaN,NaN,NaN,no,"The phrase 'voorus' references a specific event or stage in a context, not a physical location, so it is not an adverbial of place.",yes,no,no,no,yes,loc
283,8403030,13466997,5,kulgema,NaN,ad,algupool,algupoolel,"Seega kulgeb teise viisirea algupoolel meetrumist lahknev laadirütm , kus paarisarvulisi üksusi võib pidada rõhuliseks .",NaN,time,NaN,no,The phrase 'algupoolel' is not an adverbial of place because it describes a position in a sequence ('early part') rather than a physical location.,yes,no,no,no,yes,loc
474,8908257,14319555,2,algama,NaN,el,Kolmanda,Kolmandast,""" Kolmandast algavad punased .",NaN,NaN,NaN,no,"The phrase 'Kolmandast' is classified as 'no' because it refers to a starting point in a sequence or order, not a physical place.",yes,no,no,no,yes,loc
1253,4841980,7773744,1,hiilgama,NaN,in,jõuluvalgus,Jõuluvalguses,"Jõuluvalguses hiilgavad Mari Adamsoni , Ellen Hanseni , Anu Raua , Aet Ollissaare , Malle Antsoni ja paljude teiste rahvuslikke traditsioone jätkavate kunstnike kudumid .",NaN,NaN,NaN,no,The phrase 'Jõuluvalguses' describes a condition or atmosphere (Christmas light) rather than indicating a specific physical place.,yes,no,no,no,yes,loc
1474,3066873,4922295,1,kindlustama,NaN,in,ideaal,Ideaalis,Ideaalis kindlustab vaba konkurents kõigile kvaliteetse ja piisava toidu odava hinnaga .,NaN,NaN,NaN,no,"The phrase 'Ideaalis' describes an ideal situation or condition, not a physical place, so it is not classified as an adverbial of place.",yes,no,no,no,yes,loc
1947,1022717,1627207,25,kindlustama,NaN,in,ring,ringis,Eesti meeste võrkpallimeistrivõistlustel alistas Audentese Ülikool/Hermann Reisid Tartus sealse Pere Leib Cibuse 3 : 1 ning sisuliselt kindlustas voor enne lõppu kolmandas ringis esikoha .,NaN,NaN,NaN,no,"The phrase 'ringis' refers to a phase or stage in the competition and not a physical location, so it was not classified as an adverbial of place.",yes,no,no,no,yes,loc
2644,5713110,9163874,21,tõstma,NaN,in,lõppfaas,lõppfaasis,""" See sai ka kokku lepitud Euroopa Liidu tippametnikega , et / ... / Eesti selle küsimuse laua peale läbirääkimiste lõppfaasis tõstab , "" märkis ta .",NaN,NaN,NaN,no,"The phrase 'lõppfaasis' describes the timing or phase of an event rather than a location, so it was classified as 'no'.",yes,no,no,no,yes,loc
2673,451566,707158,1,peksma,läbi,ad,tee,Teel,Teel hotelli olid kurjategijad Rhedini läbi peksnud ning talt sularaha ja krediitkaardid ära varastanud .,NaN,NaN,NaN,no,"The phrase 'Teel' refers to the state of being on the way, indicating a condition or action rather than a specific place, so it is not an adverbial of place.",yes,no,no,no,yes,loc
3020,7140400,11484113,3,tajuma,NaN,in,vaikus,vaikuses,Tekkinud akvaariumitaolises vaikuses tajusin järsku kellegi sisenemist .,NaN,state,NaN,no,"It was classified as 'no' because 'vaikuses' refers to the state of being in silence, which indicates a condition or circumstance rather than a place.",yes,no,no,no,yes,loc
3063,16089346,24975555,7,oskama,NaN,in,hetk,hetkes,"Vaatamata välisele mässavale bravuurikusele oskad igas hetkes näha võimalust nautimiseks – olgu selleks siis kiire loominguline palang , pikaldane kunstiteose sünd või hoopis värvikas ja inspireeriv suhe .",NaN,time,NaN,no,"The phrase 'hetkes' refers to a moment in time rather than a physical location, so it is not an adverbial of place.",yes,no,no,no,yes,loc
3407,8399475,13461705,22,leiduma,NaN,el,algus,algusest,Näiteks on Mihkel Kampmaa avaldanud oma kirjanduslugudes kirjanike biograafiaid ning samuti leidub neid Karl August Hermanni raamatus Eesti kirjanduse ajalugu esimesest algusest meie ajani ( 1898 ) .,NaN,NaN,NaN,no,"The phrase 'algusest' refers to the starting point of time or an event and not a physical place, so it is not an adverbial of place.",yes,no,no,no,yes,loc
3965,14723710,23196506,7,sattuma,NaN,all,hiilgeajastu,hiilgeajastule,""" Karjääri algus sattus Alberto Tomba hiilgeajastule , pidin noolima peolaualt jääke .",NaN,NaN,NaN,no,"The phrase 'hiilgeajastule' refers to a time period, not a place, so it is not adverbial of place.",yes,no,no,no,yes,loc
4545,9442474,15161983,9,mõjuma,NaN,in,argipäev,argipäevas,"Võiks karta , et selline materjal mõjub tänases argipäevas nagu kirikukogu otsus Voltaire'i töölaual , kuid minu nägemust mööda tal lihtsalt puudub kõnekus .",NaN,NaN,NaN,no,"The phrase 'argipäevas' refers to a contextual state of everyday circumstances rather than a physical location, so it is not adverbial of place.",yes,no,no,no,yes,loc
4798,8740064,14029448,39,vältima,NaN,in,valimiskampaania,valimiskampaanias,"Clintoni rivaalile Bob Dole'ile oli adresseeritud hoiatus , et ta ei laseks end mõjutada sellest , mida soovivad poola , ungari jt. idaeuroopa päritolu ameeriklased ( loe : NATO kiiret laiendamist ) , vaid et ta hoopiski väldiks valimiskampaanias kogu NATO küsimust .",NaN,NaN,NaN,no,"The phrase 'valimiskampaanias' refers to the context or situation of an activity rather than a physical location, so it is not an adverbial of place.",yes,no,no,no,yes,loc
4890,2501265,4010524,2,astuma,NaN,ill,ametiaasta,ametiaastasse,"Teise ametiaastasse astus Bush populaarsuse tipus , küsitlused näitavad rekordeid löövat toetust sellele , kuidas ta oma tööga hakkama saab .",NaN,time,NaN,no,"The phrase 'ametiaastasse' describes a temporal concept ('into the second term') rather than specifying a location, so it is not adverbial of place.",yes,no,no,no,yes,loc
5300,371487,576186,9,nurjuma,NaN,in,noorus,nooruses,"Jane'i pruudiloori käristab lõhki deemonlik fuuria , Leeni nooruses nurjunud pulmapeo eel rebib selle kogemata katki õmbleja , mis muidugi tähendab õnnetust , pulmi ei tule .",NaN,NaN,NaN,no,"The phrase 'nooruses' refers to a time rather than a location, so it is not adverbial of place.",yes,no,no,no,yes,loc
7204,669013,1063707,14,seisma,NaN,el,keskaeg,keskajast,"Eesti vanimal maakirikul Ridalas on ajaloos vedanud , sest see on muutumatuna seisnud keskajast peale .",NaN,time,NaN,no,"The phrase 'keskajast' refers to a time period ('since the Middle Ages') and not to a location, so it is not adverbial of place.",yes,no,no,no,yes,loc
7286,2019241,3222233,2,mahtuma,NaN,ill,loomeaasta,loomeaastatesse,"Kontšalovski loomeaastatesse mahub ka Hollywoodi periood , kus ta tegi suurte näitlejatega esimese järgu filme .",NaN,time,NaN,no,"The phrase 'loomeaastatesse' describes a period of time, not a location or physical place.",yes,no,no,no,yes,loc
7338,13433480,21485366,12,lööma,NaN,in,MM-valiksari,MM-valiksarjas,"Tuntumatest jääb algkoosseisust välja ilmselt ka Elvir Bolic , kes eelmises MM-valiksarjas lõi neli väravat ning oli ainsa tabamuse autor Bosnia võidumängus Fääri saarte üle augustis .",NaN,NaN,NaN,no,"The phrase 'MM-valiksarjas' refers to an event or competition, not a physical place, so it is not classified as an adverbial of place.",yes,no,no,no,yes,loc
7748,2648121,4249231,13,seisma,NaN,el,olevik,olevikust,"Eesti riigipea kõneles valikutest , mille ees seisab Euroopa ning Vana Maailma olevikust ja tulevikust .",NaN,NaN,NaN,no,"The phrase 'olevikust' refers to a temporal concept (the present), not a physical location, so it is not adverbial of place.",yes,no,no,no,yes,loc
8183,4406701,7086961,5,kaaluma,NaN,in,ajalugu,ajaloos,"Seetõttu kaalub jalgpalliliit esmakordselt ajaloos , kas mitte müüa korraga kogu valiktsükli pakettpiletit , mis hõlmaks Lilleküla staadionil peetavaid mänge Inglismaa , Venemaa , Horvaatia , Iisraeli , Makedoonia ja Andorraga .",NaN,NaN,NaN,no,It was classified as 'no' because 'ajaloos' refers to a time or historical context rather than a physical location.,yes,no,no,no,yes,loc
8276,3266251,5249992,1,aitama,NaN,in,igapäevatöö,Igapäevatöös,"Igapäevatöös aitavad kollektiivlepinguseadus , töölepingu seadus , palgaseadus jt.",NaN,NaN,NaN,no,"The phrase 'Igapäevatöös' refers to the context or situation of the action, not a specific location, so it is not adverbial of place.",yes,no,no,no,yes,loc

In [8]:
df1[(df1["is_abstract"]=="yes") & (df1["is_event"]=="yes")]

Empty DataFrame
Columns: [sentence_id, head_id, head_loc, verb, verb_compound, morph_case, lemma, form, sentence, timex_tag, ekilex_tag, ner_tag, classification, explanation, is_time, is_alive, is_event, is_org, is_abstract, classification2]
Index: []

[0 rows x 20 columns]

In [9]:
at = df1[(df1["is_abstract"]=="yes") & (df1["is_time"]=="yes")]

In [10]:
at.groupby(["verb", "verb_compound", 'morph_case'], dropna=False).size().reset_index(name='count').sort_values('count', ascending=False)

           verb verb_compound morph_case  count
6   kindlustama           NaN         in      2
17       seisma           NaN         el      2
0        aitama           NaN         in      1
12      nurjuma           NaN         in      1
21    vabastama           NaN         in      1
20       tõstma           NaN         in      1
19       tajuma           NaN         in      1
18       sõitma           NaN         in      1
16      sattuma           NaN        all      1
15      ristuma           NaN         in      1
14       peksma          läbi         ad      1
13       oskama           NaN         in      1
11       mõjuma           NaN         in      1
1        algama           NaN         el      1
10      mahtuma           NaN        ill      1
9         lööma           NaN         in      1
8       leiduma           NaN         el      1
7       kulgema           NaN         ad      1
5     kajastuma           NaN         in      1
4       kaaluma           NaN         in      1
3      hiilgama           NaN         in      1
2        astuma           NaN        ill      1
22      vältima           NaN         in      1

[23 rows x 4 columns]

In [12]:
at[(at["verb"]=="seisma") & (at["morph_case"]=="el")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
7204,669013,1063707,14,seisma,NaN,el,keskaeg,keskajast,"Eesti vanimal maakirikul Ridalas on ajaloos vedanud , sest see on muutumatuna seisnud keskajast peale .",NaN,time,NaN,no,"The phrase 'keskajast' refers to a time period ('since the Middle Ages') and not to a location, so it is not adverbial of place.",yes,no,no,no,yes,loc
7748,2648121,4249231,13,seisma,NaN,el,olevik,olevikust,"Eesti riigipea kõneles valikutest , mille ees seisab Euroopa ning Vana Maailma olevikust ja tulevikust .",NaN,NaN,NaN,no,"The phrase 'olevikust' refers to a temporal concept (the present), not a physical location, so it is not adverbial of place.",yes,no,no,no,yes,loc

### kas saab olla abstract koht ja tegija samal ajal

In [8]:
df1[(df1["is_abstract"]=="yes") & (df1["is_alive"]=="yes")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
65,5552018,8902023,4,alustama,NaN,all,Eesti,Eestile,Läti on sarnaselt Eestile alustanud ettevalmistusi populatsioonigeneetika projektideks vajaliku keskkonna loomiseks .,NaN,location,LOC,no,"The phrase 'Eestile' indicates similarity or comparison, not a location, hence not adverbial of place.",no,yes,no,no,yes,loc
823,8318238,13332325,3,teatama,NaN,all,Aipin,Aipinile,Ma teatasin Aipinile : “ Su põder suri maha .,NaN,NaN,PER,no,"The phrase 'Aipinile' indicates the person being informed and not a location, so it is not an adverbial of place.",no,yes,no,no,yes,loc
824,16250999,25170290,6,eelistama,NaN,all,isik,isikule,"Sina eelistad praegu kindlasti riiki isikule , kes elab oma majas riigi metsamaal , ja väidad , et teised arvavad ka , et tema ei peaks saama .",NaN,NaN,NaN,no,"The phrase 'isikule' indicates the recipient of the preference and not a location, so it is not an adverbial of place.",no,yes,no,no,yes,loc
849,1987162,3169521,6,arutama,NaN,all,isik,isikule,"Valitsus arutab ühes korralduses ühele isikule ja teises korralduses 497 isikule Eesti kodakondsuse andmist , teatas valitsuse pressibüroo .",NaN,NaN,NaN,no,"The phrase 'isikule' refers to a recipient of something rather than a location, so it is not adverbial of place.",no,yes,no,no,yes,loc
1343,5015491,8050472,4,väitma,NaN,el,kohalolnu,kohalolnutest,"Samas väitis üks kohalolnutest , et Jüssi sõitis samuti .",NaN,NaN,NaN,no,"The phrase 'kohalolnutest' is not classified as an adverbial of place because it refers to people present, not to a location.",no,yes,no,no,yes,loc
1345,134650,225354,1,kujunema,NaN,el,Diana,Dianast,"Dianast kujunes popkultuuri ikoon , kõmulehtede meelisobjekt .",NaN,alive,PER,no,The phrase 'Dianast' is not classified as an adverbial of place because it refers to a person and not a spatial or locational context.,no,yes,no,no,yes,loc
1442,3090707,4961831,51,jääma,NaN,el,Döblini,Döblinist,"Selle näitlikustamise eest on Döblinile oma tänuvõlga väljendanud tema jünger Günter Grass , kes on talt tõesti palju õppinud , eeskätt Döblini varajastest vohavatest fantaasiaromaanidest , nagu "" Wang-Luni kolm hüpet "" või "" Mäed , mered ja gigandid "" , mille kohta näiteks Franz Kafka on öelnud : "" Döblinist jääb mulje , nagu mõistaks ta nähtavat maailma millegi täiesti ebatäiuslikuna , mida ta peab alles oma sõnaga loovalt täiendama . """,NaN,NaN,NaN,no,"The phrase 'Döblinist' refers to a person, not a location, so it is not an adverbial of place.",no,yes,no,no,yes,loc
1679,2538379,4072006,5,tulema,NaN,abl,Mõisa,Mõisalt,Peaaegu õige vastus tuleb Mõisalt : 500-600 vahel ehk 550 krooni .,NaN,NaN,PER,no,"The phrase 'Mõisalt' indicates a source or origin of the response rather than a physical location, so it is not classified as adverbial of place.",no,yes,no,no,yes,loc
1702,13434040,21486232,6,loovutama,NaN,all,lugeja,lugejaile,"Oll loovutab valged malendid lahkesti lugejaile , kuid pakub avangustaadiumis aja võitmiseks välja konkreetse seisu , kus sitsiilia kaitse nn . Polugajevski variandist väljunud partiis on tehtud 7 käiku .",NaN,NaN,NaN,no,"The phrase 'lugejaile' refers to individuals (readers) and implies the recipient of an action, not a location, so it is not an adverbial of place.",no,yes,no,no,yes,loc
2075,13032963,20852641,20,osalema,NaN,el,liikmeskond,liikmeskonnast,"Pisut varem peeti sumopühamus Ryogoku Kokugikan , kus nüüd Aki-Basho algab , veel suurem treeningukogunemine osales pool Makuuchi 42mehelisest liikmeskonnast .",NaN,alive,NaN,no,"The phrase 'liikmeskonnast' refers to a group or membership and does not indicate a location or place, so it is not classified as an adverbial of place.",no,yes,no,no,yes,loc
2301,7302171,11728706,3,saatma,NaN,all,Saluri,Salurile,Tali saatis Salurile küsimused .,NaN,NaN,PER,no,The phrase 'Salurile' refers to the recipient or indirect object of the action and does not indicate a place.,no,yes,no,no,yes,loc
2485,16847390,25924600,6,saatma,NaN,el,Häkk,Häkkist,kui sa saadad selle sõnaga Häkkist siis oled sa ise üks suur debiil ...,NaN,NaN,PER,no,The phrase 'Häkkist' is not adverbial of place because it refers to a noun and not to a location or spatial orientation.,no,yes,no,no,yes,loc
2691,1633394,2600207,15,loovutama,NaN,all,esindaja,esindajale,1993. aasta lõpus Suur-Karja 2 kinnistu tagasi saanud Werner Oldekop loovutas kolmandiku hoonest oma esindajale Selgele .,NaN,alive,NaN,no,"The phrase 'esindajale' refers to a recipient or indirect object and does not describe a location, therefore it is not an adverbial of place.",no,yes,no,no,yes,loc
3567,7323088,11755120,3,ilmuma,NaN,el,Mihhailov,Mihhailovist,"Augustis ilmus Mihhailovist küll vaid kaks pilti , see-eest astub linnaosajuht üles uudisajakirjanikuna , kes pajatab võimsast jaanitulest , Aleksei Budõlini MM-hõbedast , parima heakorraga majadest ja sellest , kuhu linnaosavalitsus on raha pannud , näiteks toetades jaanitule korraldamist .",NaN,NaN,PER,no,"The phrase 'Mihhailovist' refers to a person rather than a specific location, so it is not an adverbial of place.",no,yes,no,no,yes,loc
4041,11533871,18470751,3,säilima,NaN,ad,Helle,Hellel,"Loomulikult säilib Hellel , juhul kui Lennartiga peaks midagi juhtuma , presidendipension .",NaN,NaN,NaN,no,"The phrase 'Hellel' indicates possession or reference to a person, not a location.",no,yes,no,no,yes,loc
5000,8441597,13529693,1,tabama,NaN,el,meesjuunior,Meesjuunioridest,Meesjuunioridest tabas sama saatus Raul Seemat ( oma eelsõidus hilisema võitja Mikael Östbergi järel teine ) ja Risto Roonetit ( kolmas ) .,NaN,NaN,NaN,no,"The phrase 'Meesjuunioridest' indicates a group of people (junior men) and does not specify a physical location, so it is not an adverbial of place.",no,yes,no,no,yes,loc
5011,599226,950206,11,säilima,NaN,ad,Villarreali,Villarrealil,"Väikesed pääsemislootused säilivad viimati 3 : 0 Racing Santanderi alistanud Villarrealil , kellel on 35 punkti .",NaN,NaN,LOC,no,"The phrase 'Villarrealil' refers to the team Villarreal and is not indicating a place, so it is not classified as an adverbial of place.",no,yes,no,yes,yes,loc
5416,13585168,21722907,5,arutama,NaN,all,kantsler,kantslerile,Valitsus arutab teisipäeval rahandusministeeriumi kantslerile Agu Lellepile kohtuvaidluses Kiljakiga volituse andmist .,NaN,alive,NaN,no,"The phrase 'kantslerile' refers to a person and not a location, so it is not adverbial of place.",no,yes,no,no,yes,loc
5816,12544462,20077637,4,kuuluma,NaN,ill,arst,Arstidesse,"1971 asutatud Piirideta Arstidesse kuulub üle kahe tuhande vabatahtliku , kes annavad abi ligi 70 riigis .",NaN,alive,NaN,no,"The phrase 'Arstidesse' refers to a group or entity, not a spatial location, so it is not an adverbial of place.",no,yes,no,yes,yes,loc
6044,3310739,5323133,4,sõnama,NaN,all,maarivi,Maarivile,"Üks allikas sõnas Maarivile , et tanki tulistamine võis detoneerida lõhkeaine , mis oli samasse piirkonda palestiinlaste poolt peidetud .",NaN,NaN,ORG,no,"The word 'Maarivile' refers to a recipient rather than a location, so it is not classified as an adverbial of place.",no,yes,no,no,yes,loc
6048,7519214,12074463,17,tooma,NaN,all,Eiffel,Eiffelile,"Tornist kujunes pikkamisi ( eks tänu ka hoogsale mahategemisele ) Pariisi sümbol , Panama kanal aga Eiffelile kuulsust ei toonud .",NaN,NaN,NaN,no,"The word 'Eiffelile' refers to an entity or person rather than a place, so it is not classified as an adverbial of place.",no,yes,no,no,yes,loc
7407,4657617,7484329,5,vedama,NaN,all,minister,ministritele,"Olen vedanud toitu nii ministritele , riigikogulastele kui linnapeadele .",NaN,alive,NaN,no,"The phrase 'ministritele' refers to recipients (ministers) rather than a location, so it is not an adverbial of place.",no,yes,no,no,yes,loc
7696,4620236,7425073,17,puuduma,NaN,ad,ER,ER-il,"Kaks aastat tagasi osteti küll Saksamaalt 23 diiselmootorit , kuid seejuures ei arvestatud asjaolu , et ER-il puuduvad vahendid mootorite paigaldamiseks .",NaN,NaN,ORG,no,"The phrase 'ER-il' was classified as 'no' because it refers to an entity or organization rather than a specific location, so it is not an adverbial of place.",no,yes,no,yes,yes,loc
7937,5632192,9032042,11,süvendama,NaN,in,lastekodujuht,lastekodujuhtides,"TALLINN , 5. august ( EPLO ) - Hinnatõusuralli süvendab lastekodujuhtides hirmu , et isegi kui riik annab neile lisaeelarvest kümme miljonit krooni , otsustavad koolitatud kasvatajad otsida tasuvamat ametit , kirjutab Postimees .",NaN,NaN,NaN,no,The phrase 'lastekodujuhtides' is not classified as an adverbial of place because it describes a group of people rather than a location.,no,yes,no,no,yes,loc
8289,13572567,21702428,11,tõstma,NaN,in,kuulaja,kuulajais,""" Jõudsin tee enamvähem lahti saada , "" tõstab Kaerama kuulajais põnevust .",NaN,alive,NaN,no,"The phrase 'kuulajais' is not an adverbial of place because it refers to the listeners as a group of people, not to a location.",no,yes,no,no,yes,loc
9062,14498565,22927838,16,tooma,kaasa,all,inimkond,inimkonnale,"Kaks aastat tagasi ajakirjas National Geographic ilmunud kohviteemalises artiklis väidetakse , et suur kohvijoomine on inimkonnale kaasa toonud kroonilise unedefitsiidi – kui enne moodsaid aegu reguleerisid meie ärkvelolekutunnet loomulik päevavalgus ja aastaajad , siis kapitalistlikus ühiskonnas määrab töötunnid kell .",NaN,NaN,NaN,no,"The phrase 'inimkonnale' refers to the group of people impacted and not to a specific place, thus it is not adverbial of place.",no,yes,no,no,yes,loc
9298,8345040,13372428,18,saatma,NaN,all,Allik,Allikule,"Kui Allik kunagi Eesti NATOsse astumise vastu sõna võttis , siis tundis Liiv temaga solidaarsust ja saatis Allikule NATO-vastase luuletuse .",NaN,NaN,PER,no,"The phrase 'Allikule' indicates a recipient of the poem (a person), not a physical place, so it is not an adverbial of place.",no,yes,no,no,yes,loc
9676,11584238,18549303,5,soovima,NaN,abl,Hussein,Husseinilt,AP-BNS teatel soovib Netanyahu Husseinilt nõusolekut kuue- kuni üheksakuuliste kiirläbirääkimiste alustamiseks Palestiinaga .,NaN,NaN,PER,no,The phrase 'Husseinilt' is classified as 'no' because it refers to a source or origin of agreement rather than a location.,no,yes,no,no,yes,loc

In [9]:
df1[(df1["is_abstract"]=="yes") & (df1["is_org"]=="yes")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
60,11396051,18262044,16,alluma,NaN,all,fraktsioon,fraktsioonile,"Demokraatlikus parlamentarismis jääb iga poliitiline minister alati kahe tule vahele , sest ta allub nii fraktsioonile parlamendis kui ka peaministrile valitsuses .",NaN,NaN,NaN,no,"The phrase 'fraktsioonile' refers to whom the minister is subordinated, not a location, hence not adverbial of place.",no,no,no,yes,yes,loc
433,4535331,7290055,10,saama,NaN,abl,Ford,Fordilt,"Keretarnijateks on ikka Lola ja Reynard , mootoreid saab Fordilt , Hondalt ja Toyotalt .",NaN,NaN,NaN,no,"The phrase 'Fordilt' indicates the source or provider of the engines and not a place, so it is not adverbial of place.",no,no,no,yes,yes,loc
743,2166662,3460881,2,tulema,NaN,all,BREM,BREM-ile,""" BREM-ile ei ole tulnud ühtegi kirja ega kutset konkursile ega ole me ka mujalt selle toimumisest kuulnud , "" ütles Toomas Õispuu .",NaN,NaN,NaN,no,"The phrase 'BREM-ile' indicates the recipient of an action (to whom something was not sent), not a physical location, so it was not classified as an adverbial of place.",no,no,no,yes,yes,loc
748,6552200,10541361,20,tooma,NaN,all,Peugeot,Peugeot'le,"Peugeot' sõitjaist oli Marcus Grönholm sõidu pooleli jätnud juba avapäeva järel , kaheksandaks tulnud Nicolas Bernardi tõi aga Peugeot'le vaid ühe punkti .",NaN,NaN,PER,no,"The phrase 'Peugeot'le' refers to the entity benefiting from an action, not a location, so it was not classified as an adverbial of place.",no,no,no,yes,yes,loc
1072,808276,1289456,5,kuuluma,NaN,all,Finnlinesi,Finnlinesile,"Läänemerel 70 kaubalaevaga opereerivale Finnlinesile kuulub 23 laeva , millest Soome lipu all seilab praegu 14 alust .",NaN,NaN,LOC,no,"The phrase 'Finnlinesile' indicates possession or ownership, not a location, so it is not an adverbial of place.",no,no,no,yes,yes,loc
1237,3617325,5825099,10,takistama,NaN,ad,Microsoft,Microsoftil,"Kohtu otsus aitab kaasa konkurentsi kindlustamisele turul ja takistab Microsoftil saavutada ebaõiglast eelispositsiooni , ütles Reno .",NaN,NaN,LOC,no,"The phrase 'Microsoftil' indicates possession or association, not a physical location, so it is not adverbial of place.",no,no,no,yes,yes,loc
1398,6195759,9949064,22,võtma,NaN,all,Päevaleht,Päevalehele,""" Idee minna Siberisse tuli 14 aastat tagasi aset leidnud ekspeditsioonist , kui eestlaste matmiskohta Norilskis rajati mälestusmemoriaal , "" ütles Päevalehele retkest osa võtnud ja reisikirjanikuna tuntust kogunud Marko Kaldur .",NaN,NaN,ORG,no,"The phrase 'Päevalehele' was classified as 'no' because it designates a recipient of communication, not a spatial or physical place.",no,no,no,yes,yes,loc
1415,14422416,22842624,11,puuduma,NaN,ad,PRIA,PRIAl,"PRIA teabe – ja arendusosakonna juhataja Heli Raametsa sõnul puuduvad PRIAl andmed , kui palju Läänemaal sügisel talivilja maha külvati ja kui palju sellest on hävinud .",NaN,NaN,NaN,no,"The phrase 'PRIAl' indicates possession or a source of data rather than a location, thus it is not adverbial of place.",no,no,no,yes,yes,loc
2107,15376531,24017278,4,käima,NaN,abl,FIFA,FIFA-lt,"Väljakul käis ka FIFA-lt Florasse naasmiseks vajalikku paberit ootav Vjatšeslav Zahovaiko , kuid talle anti Goesi sõnul lihtsalt mängupraktikat .",NaN,NaN,NaN,no,"The phrase 'FIFA-lt' refers to an institution, not to a location, so it was classified as 'no'.",no,no,no,yes,yes,loc
2486,1833625,2918762,1,jätma,NaN,in,Moody,Moody's,Moody's jättis Optivale Forekspanga reitingu,NaN,NaN,LOC,no,The phrase 'Moody's' is not adverbial of place because it refers to a name or entity rather than indicating a place.,no,no,no,yes,yes,loc
2891,1348294,2143822,19,sõnama,NaN,all,raadiojaam,raadiojaamale,""" Seda on peaaegu sama palju , kui kõik Moskva piirkonnas makstavad pensionid , "" sõnas Putin usutluses raadiojaamale Majak .",NaN,NaN,NaN,no,"The phrase 'raadiojaamale' refers to the recipient of the statement rather than a location, so it was classified as 'no'.",no,no,no,yes,yes,loc
2909,4188835,6741519,3,edastama,NaN,all,kolleegium,kolleegiumile,"Põhiseaduslikkuse järelevalve kolleegiumile edastas küsimuse halduskohus , paludes riigikohtul kontrollida vanemahüvitiseseaduse § 3 lg 7 ja § 7 lg 1 p 3 vastavust põhiseadusele .",NaN,NaN,NaN,no,"The phrase 'kolleegiumile' indicates a recipient (the constitutional review chamber) rather than a physical location, so it is not an adverbial of place.",no,no,no,yes,yes,loc
4038,10927861,17501547,3,tegutsema,NaN,ad,XXL,XXLil,"Praegu tegutseb XXLil Eestis üks internetiportaal , mille turuosa üritatakse lähiajal suurendada .",NaN,NaN,NaN,no,The phrase 'XXLil' refers to an entity and does not indicate a location or place.,no,no,no,yes,yes,loc
4146,488683,768035,18,lausuma,NaN,all,Reuters,Reutersile,""" Mängisime esimesel poolajal paremini kui teisel , kuid kummalisel kombel piisas sellest võiduks , "" lausus Reutersile ManU peatreener Alex Ferguson .",NaN,NaN,ORG,no,"It was classified as 'no' because 'Reutersile' indicates the recipient of the statement, not a location.",no,no,no,yes,yes,loc
4165,10980710,17587318,8,vajama,NaN,abl,Liidu,Liidult,"Ligipääs ostujõulisele turule , mida me Euroopa Liidult kõige enam vajame , on meil ju olemas kuis muidu pääseks juba praegu 80% Eesti ekspordist ELi ?",NaN,NaN,NaN,no,"The phrase 'Liidult' indicates the European Union as a source or giver, not a physical location, so it is not an adverbial of place.",no,no,no,yes,yes,loc
4257,2280292,3650300,5,ostma,NaN,in,iga,EAS,Väljavalitud piltide kasutusõiguse ostab EAS reklaammaterjalide illustreerimiseks .,NaN,NaN,NaN,no,"'EAS' is not adverbial of place because it refers to an entity (Estonian Enterprise), not a spatial location.",no,no,no,yes,yes,loc
4676,11574025,18533797,3,hoidma,NaN,all,ühendus,ühendusele,Ammusele sõbrale ühendusele Hoia Eesti Merd lisandusid Fuji Filmi Eesti esindus ja AS Südvester .,NaN,NaN,NaN,no,The phrase 'ühendusele' is not adverbial of place as it refers to the recipient of an addition (the connection) rather than specifying a location.,no,no,no,yes,yes,loc
5011,599226,950206,11,säilima,NaN,ad,Villarreali,Villarrealil,"Väikesed pääsemislootused säilivad viimati 3 : 0 Racing Santanderi alistanud Villarrealil , kellel on 35 punkti .",NaN,NaN,LOC,no,"The phrase 'Villarrealil' refers to the team Villarreal and is not indicating a place, so it is not classified as an adverbial of place.",no,yes,no,yes,yes,loc
5020,11360881,18202686,13,kasvama,NaN,all,opositsioonipartei,opositsiooniparteile,Valitsuse märtsis tellitud arvamusuuringu järgi on valimisealiste Eesti kodanike toetus Riigikogu suurimale opositsiooniparteile Keskerakonnale kasvanud sügisega võrreldes viis protsenti .,NaN,alive,NaN,no,The phrase 'opositsiooniparteile' was classified as 'no' because it specifies the beneficiary or recipient rather than a location.,no,no,no,yes,yes,loc
5039,1217791,1936244,14,tunnistama,NaN,all,SLÕL,SLÕL- le,"Jaanus Karm pole kunagi varem oma saatuse kohta arvamust avaldanud , kuid tunnistas SLÕL- le : "" Olen kolm aastat seda otsust oodanud .",NaN,NaN,ORG,no,"The phrase 'SLÕL- le' indicates the recipient of the statement rather than a physical location, so it is not an adverbial of place.",no,no,no,yes,yes,loc
5064,2097129,3346746,8,laekuma,NaN,all,BSA,BSA-le,"Info võimalikust ebaseaduslikust tarkvara kasutamisest laekus Läti BSA-le , kes edastas selle Läti politseile ning kuivõrd selgus , et Pristise kontorid asuvad kõigis kolmes Balti riigis , edastatigi informatsioon kontrollimiseks ka Eesti ja Leedu politseile .",NaN,NaN,ORG,no,"The phrase 'BSA-le' indicates a recipient rather than a physical location, so it was classified as 'no'.",no,no,no,yes,yes,loc
5083,12522632,20044850,5,tooma,NaN,all,NBA,NBA-le,Invasioon Kanadasse on toonud NBA-le kümnetesse miljonitesse dollaritesse ulatuva kahjumi - põhjuseks Kanada dollari nõrgenemine !,NaN,location,NaN,no,"The phrase 'NBA-le' indicates a recipient or target, not a physical location, so it is not an adverbial of place.",no,no,no,yes,yes,loc
5135,5029582,8072733,3,ütlema,NaN,all,FBI,FBI-le,"Beamer ütles FBI-le , et üks kaaperdajatest , kes asub lennuki tagumises osas , on teatanud , et tal on pomm keha ümber kinnitatuna .",NaN,location,ORG,no,"'FBI-le' was classified as 'no' because it refers to the recipient of the communication, not a spatial or physical place.",no,no,no,yes,yes,loc
5201,1042859,1658426,3,soovima,NaN,abl,NATO,NATOlt,"Minsk soovib NATOlt kinnitust julgeolekutagatiste kohta ja lubadust mitte Valgevene vastu jõudu kasutada ega jõuga ähvardada , lisas Rõbakov .",NaN,location,ORG,no,"The phrase 'NATOlt' refers to the entity from which confirmation is requested, not to a physical location.",no,no,no,yes,yes,loc
5385,5301162,8504781,21,ostma,NaN,in,Securita,Securitas,"Kuna taastamine pole vanade eksponaatide puhul võimalik , ostis vabaõhumuuseum kindlustuse asemel mullu riigihankekonkursi läbi 3,5 miljoni krooni eest turvafirmalt Securitas elektroonilise valvesüsteemi , mis oli Langi sõnul ka Securitase hooldada .",NaN,NaN,LOC,no,"The phrase 'Securitas' refers to a company name, not a location or a place, so it is not an adverbial of place.",no,no,no,yes,yes,loc
5408,17477316,26791938,6,kuuluma,NaN,all,CIA,CIAle,Ka see lennuk olevat kuulunud CIAle .,NaN,location,NaN,no,"The phrase 'CIAle' indicates a recipient or target rather than a physical place, so it is not adverbial of place.",no,no,no,yes,yes,loc
5413,4406652,7086895,3,tulema,NaN,in,Francai,Francais,"Jah , Francais de Jeux'st tuli meile noor austraallane Mark Renshaw .",NaN,NaN,LOC,no,"The phrase 'Francais' refers to a name and does not indicate a location, so it is not adverbial of place.",no,no,no,yes,yes,loc
5816,12544462,20077637,4,kuuluma,NaN,ill,arst,Arstidesse,"1971 asutatud Piirideta Arstidesse kuulub üle kahe tuhande vabatahtliku , kes annavad abi ligi 70 riigis .",NaN,alive,NaN,no,"The phrase 'Arstidesse' refers to a group or entity, not a spatial location, so it is not an adverbial of place.",no,yes,no,yes,yes,loc
5887,8913365,14328171,11,kavandama,NaN,all,vanalinnastuudio,Vanalinnastuudiole,"Sauna tänav 10 asuval kinnistul , kuhu Vanalinna Teatrimaja Sihtasutus Vanalinnastuudiole uut maja kavandas , tegid arheoloogid kuni 13. sajandi kihistuseni põhjalikke uuringuid .",NaN,NaN,ORG,no,"The phrase 'Vanalinnastuudiole' was classified as 'no' because it refers to a recipient or entity, not a location.",no,no,no,yes,yes,loc
5939,673717,1071320,24,säilima,NaN,ad,FOM,FOM-il,"Maja ostust huvituva Saksa kinnisvaraarendusfirma Future Office Management ( FOM ) esindaja , advokaadibüroo Tark & Co advokaat Toomas Taube sõnas , et FOM-il on huvi hinnalise kinnistu vastu säilinud .",NaN,NaN,ORG,no,"The phrase 'FOM-il' indicates possession or association, not a place, so it is not adverbial of place.",no,no,no,yes,yes,loc
6107,4012573,6459180,5,tegutsema,NaN,ad,TPü,TPü-l,Esimese poolaja lõpul tegutses TPü-l hästi Janne Rits ja vaheajale mindi AGA/Feeri minimaalses eduseisus 32 : 31.,NaN,NaN,NaN,no,"The phrase 'TPü-l' indicates possession or association with TPü rather than specifying a physical location, so it is not an adverbial of place.",no,no,no,yes,yes,loc
6148,10001694,16043904,5,jääma,välja,el,jaemüügikett,jaemüügikettidest,Suurematest Eesti kapitalile kuuluvatest jaemüügikettidest jääb ristkasutussüsteemist esialgu välja 11 Favora kaubamärgi all tegutsevat tanklat .,NaN,NaN,NaN,no,"The phrase 'jaemüügikettidest' refers to the source of exclusion ('from retail chains') and does not describe a location, hence it is not classified as adverbial of place.",no,no,no,yes,yes,loc
6319,2305916,3693168,11,tasuma,NaN,all,erafirma,erafirmale,"Pakosta kinnitas eile , et leping , mille alusel ta erafirmale tasus , oli korrektselt vormistatud ja linnakantseleis olemas .",NaN,location,NaN,no,The phrase 'erafirmale' was classified as 'no' because it refers to a recipient or beneficiary of payment rather than a location or place.,no,no,no,yes,yes,loc
6446,1554515,2473538,15,kaevama,NaN,all,salateenistus,salateenistustele,"Populaarsete spiooniromaanide autor John Le Carre tunnistas avalikult , et ta oli kaevanud ülikooliaastatel salateenistustele oma kaasõppurite peale .",NaN,location,NaN,no,The phrase 'salateenistustele' is not classified as an adverbial of place because it denotes the indirect object (to whom) rather than a spatial location.,no,no,no,yes,yes,loc
6662,15248752,23816690,5,jõudma,ette,el,BE,BEst,Seega jõuab SE peaegi BEst ette .,NaN,NaN,NaN,no,"The phrase 'BEst' refers to a noun and does not describe a location or place, so it is not classified as an adverbial of place.",no,no,no,yes,yes,loc
7092,611796,970125,1,tegema,NaN,all,Estiko,Estikole,Estikole kahju teinud Seli tehingute näitena tõi Hellenurm Tartu kaubahalli ostmise .,NaN,NaN,NaN,no,"The phrase 'Estikole' refers to the entity or organization Estiko, not a location.",no,no,no,yes,yes,loc
7195,5231576,8392673,12,sõnama,NaN,all,internetiportaal,internetiportaalile,"Ivaniševic jalgpalli mängimise eest raha ei saa , kuid tennisist sõnas internetiportaalile Dailysoccer , et on ülimalt õnnelik , kui teda kasvõi üheks minutiks ametlikus mängus platsile lubatakse .",NaN,NaN,NaN,no,The phrase 'internetiportaalile' was classified as 'no' because it signifies a direction or target (to an internet portal) rather than denoting a physical location.,no,no,no,yes,yes,loc
7406,4240795,6824528,4,tegema,NaN,all,ELS,ELS-ile,Lisaks linnukasvatusvaldkonnale teevad ELS-ile muret ka sigade ja piimaveiste kasvatamise tingimused .,NaN,NaN,ORG,no,"The phrase 'ELS-ile' indicates a recipient (the organization ELS) rather than a physical place, so it is not an adverbial of place.",no,no,no,yes,yes,loc
7696,4620236,7425073,17,puuduma,NaN,ad,ER,ER-il,"Kaks aastat tagasi osteti küll Saksamaalt 23 diiselmootorit , kuid seejuures ei arvestatud asjaolu , et ER-il puuduvad vahendid mootorite paigaldamiseks .",NaN,NaN,ORG,no,"The phrase 'ER-il' was classified as 'no' because it refers to an entity or organization rather than a specific location, so it is not an adverbial of place.",no,yes,no,yes,yes,loc
8049,815650,1301449,8,kuuluma,NaN,all,BMW,BMW-le,Legendaarne Inglise automark Rover kuulub eelmisest aastast BMW-le .,NaN,location,NaN,no,"The phrase 'BMW-le' refers to ownership or belonging, not a physical location, thus it is not adverbial of place.",no,no,no,yes,yes,loc
8951,350443,541744,1,minema,NaN,all,AP,AP-le,"AP-le läks preemia pressifotode eest , mis olid tehtud Kenyas ja Tansaanias asuvate USA suursaatkondade pommirünnakutest .",NaN,location,ORG,no,The phrase 'AP-le' was classified as not adverbial of place because it designates a recipient ('to AP') rather than indicating a location.,no,no,no,yes,yes,loc
9297,15144787,23687157,8,teatama,NaN,all,LRTN,LRTNile,"Ta lisas , et PBK teatas kirjas LRTNile , et ei vaidlusta Balti riikide iseseisvust ning on valmis korraldama diskussiooni , kutsudes Balti riikide okupeerimise küsimuses arvamust avaldama Baltimaade ja teiste Euroopa Liidu riikide ajaloolasi .",NaN,NaN,ORG,no,"The phrase 'LRTNile' represents a recipient of communication rather than a location, so it is not an adverbial of place.",no,no,no,yes,yes,loc
9299,10776113,17261845,7,esitama,NaN,all,Primetime,Primetime'ile,"TV 1 esitas Piheli sõnul kohe Primetime'ile järelepärimise , kas info vastab tõele , ja sai jaatava vastuse .",NaN,NaN,LOC,no,"The phrase 'Primetime'ile' refers to a recipient (a media entity), not a location, so it is not an adverbial of place.",no,no,no,yes,yes,loc
9674,3993141,6427609,4,võlgnema,NaN,all,kontsern,kontsernile,"Werol võlgneb Kilgi kontsernile 72 miljonit krooni ning kuna firmal seda summat tasuda pole , läheb vara müüki .",NaN,NaN,NaN,no,The phrase 'kontsernile' is classified as 'no' because it indicates a recipient (to the holding company) rather than a location.,no,no,no,yes,yes,loc
9709,9553516,15334783,3,juhtuma,NaN,ad,justiitsministeerium,justiitsministeeriumil,Tegelikult juhtus justiitsministeeriumil äpardus .,NaN,location,NaN,no,It was classified as 'no' because 'justiitsministeeriumil' refers to the ministry as an entity rather than a specific location.,no,no,no,yes,yes,loc

In [14]:
ao = df1[(df1["is_abstract"]=="yes") & (df1["is_org"]=="yes")]
aa = df1[(df1["is_abstract"]=="yes") & (df1["is_alive"]=="yes")]

In [13]:
ao.groupby(["verb", "verb_compound", 'morph_case'], dropna=False).size().reset_index(name='count').sort_values('count', ascending=False)

          verb verb_compound morph_case  count
11     kuuluma           NaN        all      3
18     puuduma           NaN         ad      2
28       tooma           NaN        all      2
17       ostma           NaN         in      2
21     säilima           NaN         ad      2
22      sõnama           NaN        all      2
26      tegema           NaN        all      2
27   tegutsema           NaN         ad      2
29      tulema           NaN        all      1
19       saama           NaN        abl      1
30      tulema           NaN         in      1
31  tunnistama           NaN        all      1
25     teatama           NaN        all      1
24      tasuma           NaN        all      1
23   takistama           NaN         ad      1
32      vajama           NaN        abl      1
33    võlgnema           NaN        all      1
34       võtma           NaN        all      1
20     soovima           NaN        abl      1
0       alluma           NaN        all      1
1     edastama           NaN        all      1
16      minema           NaN        all      1
15     lausuma           NaN        all      1
14     laekuma           NaN        all      1
13       käima           NaN        abl      1
12     kuuluma           NaN        ill      1
10   kavandama           NaN        all      1
9      kasvama           NaN        all      1
8      kaevama           NaN        all      1
7       jõudma          ette         el      1
6        jääma         välja         el      1
5        jätma           NaN         in      1
4      juhtuma           NaN         ad      1
3       hoidma           NaN        all      1
2      esitama           NaN        all      1
35      ütlema           NaN        all      1

[36 rows x 4 columns]

In [15]:
ao[(ao["verb"]=="kuuluma") & (ao["morph_case"]=="all")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
1072,808276,1289456,5,kuuluma,NaN,all,Finnlinesi,Finnlinesile,"Läänemerel 70 kaubalaevaga opereerivale Finnlinesile kuulub 23 laeva , millest Soome lipu all seilab praegu 14 alust .",NaN,NaN,LOC,no,"The phrase 'Finnlinesile' indicates possession or ownership, not a location, so it is not an adverbial of place.",no,no,no,yes,yes,loc
5408,17477316,26791938,6,kuuluma,NaN,all,CIA,CIAle,Ka see lennuk olevat kuulunud CIAle .,NaN,location,NaN,no,"The phrase 'CIAle' indicates a recipient or target rather than a physical place, so it is not adverbial of place.",no,no,no,yes,yes,loc
8049,815650,1301449,8,kuuluma,NaN,all,BMW,BMW-le,Legendaarne Inglise automark Rover kuulub eelmisest aastast BMW-le .,NaN,location,NaN,no,"The phrase 'BMW-le' refers to ownership or belonging, not a physical location, thus it is not adverbial of place.",no,no,no,yes,yes,loc

In [16]:
ao[(ao["verb"]=="puuduma") & (ao["morph_case"]=="ad")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
1415,14422416,22842624,11,puuduma,NaN,ad,PRIA,PRIAl,"PRIA teabe – ja arendusosakonna juhataja Heli Raametsa sõnul puuduvad PRIAl andmed , kui palju Läänemaal sügisel talivilja maha külvati ja kui palju sellest on hävinud .",NaN,NaN,NaN,no,"The phrase 'PRIAl' indicates possession or a source of data rather than a location, thus it is not adverbial of place.",no,no,no,yes,yes,loc
7696,4620236,7425073,17,puuduma,NaN,ad,ER,ER-il,"Kaks aastat tagasi osteti küll Saksamaalt 23 diiselmootorit , kuid seejuures ei arvestatud asjaolu , et ER-il puuduvad vahendid mootorite paigaldamiseks .",NaN,NaN,ORG,no,"The phrase 'ER-il' was classified as 'no' because it refers to an entity or organization rather than a specific location, so it is not an adverbial of place.",no,yes,no,yes,yes,loc

In [17]:
ao[(ao["verb"]=="ostma") & (ao["morph_case"]=="in")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
4257,2280292,3650300,5,ostma,NaN,in,iga,EAS,Väljavalitud piltide kasutusõiguse ostab EAS reklaammaterjalide illustreerimiseks .,NaN,NaN,NaN,no,"'EAS' is not adverbial of place because it refers to an entity (Estonian Enterprise), not a spatial location.",no,no,no,yes,yes,loc
5385,5301162,8504781,21,ostma,NaN,in,Securita,Securitas,"Kuna taastamine pole vanade eksponaatide puhul võimalik , ostis vabaõhumuuseum kindlustuse asemel mullu riigihankekonkursi läbi 3,5 miljoni krooni eest turvafirmalt Securitas elektroonilise valvesüsteemi , mis oli Langi sõnul ka Securitase hooldada .",NaN,NaN,LOC,no,"The phrase 'Securitas' refers to a company name, not a location or a place, so it is not an adverbial of place.",no,no,no,yes,yes,loc

In [18]:
ao[(ao["verb"]=="tulema") & (ao["morph_case"]=="in")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
5413,4406652,7086895,3,tulema,NaN,in,Francai,Francais,"Jah , Francais de Jeux'st tuli meile noor austraallane Mark Renshaw .",NaN,NaN,LOC,no,"The phrase 'Francais' refers to a name and does not indicate a location, so it is not adverbial of place.",no,no,no,yes,yes,loc

In [15]:
aa.groupby(["verb", "verb_compound", 'morph_case'], dropna=False).size().reset_index(name='count').sort_values('count', ascending=False)

         verb verb_compound morph_case  count
7   loovutama           NaN        all      2
10     saatma           NaN        all      2
1     arutama           NaN        all      2
13    säilima           NaN         ad      2
0    alustama           NaN        all      1
14     sõnama           NaN        all      1
22     vedama           NaN        all      1
21     tõstma           NaN         in      1
20     tulema           NaN        abl      1
19      tooma           NaN        all      1
18      tooma         kaasa        all      1
17    teatama           NaN        all      1
16     tabama           NaN         el      1
15  süvendama           NaN         in      1
12    soovima           NaN        abl      1
11     saatma           NaN         el      1
9     puuduma           NaN         ad      1
8     osalema           NaN         el      1
6     kuuluma           NaN        ill      1
5    kujunema           NaN         el      1
4       jääma           NaN         el      1
3      ilmuma           NaN         el      1
2   eelistama           NaN        all      1
23     väitma           NaN         el      1

[24 rows x 4 columns]

In [19]:
aa[(aa["verb"]=="loovutama") & (aa["morph_case"]=="all")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
1702,13434040,21486232,6,loovutama,NaN,all,lugeja,lugejaile,"Oll loovutab valged malendid lahkesti lugejaile , kuid pakub avangustaadiumis aja võitmiseks välja konkreetse seisu , kus sitsiilia kaitse nn . Polugajevski variandist väljunud partiis on tehtud 7 käiku .",NaN,NaN,NaN,no,"The phrase 'lugejaile' refers to individuals (readers) and implies the recipient of an action, not a location, so it is not an adverbial of place.",no,yes,no,no,yes,loc
2691,1633394,2600207,15,loovutama,NaN,all,esindaja,esindajale,1993. aasta lõpus Suur-Karja 2 kinnistu tagasi saanud Werner Oldekop loovutas kolmandiku hoonest oma esindajale Selgele .,NaN,alive,NaN,no,"The phrase 'esindajale' refers to a recipient or indirect object and does not describe a location, therefore it is not an adverbial of place.",no,yes,no,no,yes,loc

In [20]:
aa[(aa["verb"]=="saatma") & (aa["morph_case"]=="all")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
2301,7302171,11728706,3,saatma,NaN,all,Saluri,Salurile,Tali saatis Salurile küsimused .,NaN,NaN,PER,no,The phrase 'Salurile' refers to the recipient or indirect object of the action and does not indicate a place.,no,yes,no,no,yes,loc
9298,8345040,13372428,18,saatma,NaN,all,Allik,Allikule,"Kui Allik kunagi Eesti NATOsse astumise vastu sõna võttis , siis tundis Liiv temaga solidaarsust ja saatis Allikule NATO-vastase luuletuse .",NaN,NaN,PER,no,"The phrase 'Allikule' indicates a recipient of the poem (a person), not a physical place, so it is not an adverbial of place.",no,yes,no,no,yes,loc

In [21]:
df1[(df1["classification2"]=="UNK")]

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,timex_tag,ekilex_tag,ner_tag,classification,explanation,is_time,is_alive,is_event,is_org,is_abstract,classification2
21,2076950,3314189,11,hoidma,NaN,in,alatoitlus,alatoitluses,"See on olukord , mis hoiab suure hulga eesti lapsi alatoitluses , rääkimata täiskasvanutest .",NaN,NaN,NaN,no,"The phrase 'alatoitluses' describes a condition or state rather than a physical location, so it is not adverbial of place.",no,no,no,no,no,UNK
25,9061330,14569548,9,ennustama,NaN,all,ajakiri,ajakirjale,Keskkooli direktor Tõnu Valdma ennustas seda juba mullu ajakirjale Luup antud intervjuus .,NaN,NaN,NaN,no,"The phrase 'ajakirjale' indicates a recipient of the action rather than a physical location, so it is not adverbial of place.",no,no,no,no,no,UNK
32,6340453,10188183,14,kontrollima,NaN,el,kapitalimaht,kapitalimahust,"Arreteeritud Platon Lebedev juhib Jukose finantskeskuseks olevat gruppi Menatep , mis kontrollib Jukose kapitalimahust 61 protsenti moodustavat eraomanike vara .",NaN,NaN,NaN,no,"The phrase 'kapitalimahust' refers to a proportion of capital, which is not a reference to a location, hence it is not an adverbial of place.",no,no,no,no,no,UNK
34,14437832,22868258,22,müüma,NaN,el,alustamine,alustamisest,"b ) meierei , kes seda võimalust kasutab , ei müü lõssipulbrit sekkumisasutusele nelja nädala jooksul alates käesolevas taandes osutatud tegevuse alustamisest ning teatab inspekteerimisasutusele enne tegevuse alustamist selle alguskuupäeva .",NaN,NaN,NaN,no,"The phrase 'alustamisest' refers to the starting of an action, not a specific place, so it is not an adverbial of place.",no,no,no,no,no,UNK
36,3490887,5621274,15,vähenema,NaN,all,650000,650 000-le,Tööga hõivatud inimeste arv on aga turumajanduslikele suhetele üleminekul vähenenud 200 000 võrra - 850 000-lt 650 000-le .,NaN,NaN,NaN,no,"The phrase '650 000-le' represents a numerical value or quantity, not a location, therefore it is not an adverbial of place.",no,no,no,no,no,UNK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9981,17978857,27357830,5,jääma,NaN,el,100%,100%st,"Kui ELi otsetoetused jäävad 100%st väiksemaks , tuleb toetussumma eraldada Eesti riigieelarvest , et meie põllumeestel oleks liidus võrdsed tingimused .",NaN,NaN,NaN,no,"The phrase '100%st' is not specifying a location, so it's not an adverbial of place.",no,no,no,no,no,UNK
9984,5262886,8442442,6,käima,ära,ad,rekordmadal,rekordmadalal,Telekomi aktsia käis päevasiseselt ära rekordmadalal 70 krooni tasemel .,NaN,NaN,NaN,no,"The phrase 'rekordmadalal' describes a level or state, not a place, so it's not an adverbial of place.",no,no,no,no,no,UNK
9995,981021,1562806,8,levima,NaN,ad,selgitus,selgitusel,"Hansapanga suhtekorraldajate Kristi Liiva ja Ando Noormetsa selgitusel levis tehnilise rikke versioon esmaspäeva hommikul seetõttu , et panga klienditoe töötajatel ei olnud enne turvajuurdluse lõppu juhtunu kohta täpset infot .",NaN,NaN,NaN,no,"The phrase 'selgitusel' explains the means or reason of an action and does not indicate a location, so it is not an adverbial of place.",no,no,no,no,no,UNK
9998,4825664,7748191,4,hüppama,NaN,el,loodetud,loodetust,"Mitmedki mehed hüppasid loodetust kümmekond meetrit vähem , kuni Masahiko Harada tõusis 115meetrise hüppega teiseks .",NaN,NaN,NaN,no,"The phrase 'loodetust' refers to a comparison of expectations, not a specific location, so it is not an adverbial of place.",no,no,no,no,no,UNK
9999,1412007,2245986,10,kinnitama,NaN,all,isikuomadus,isikuomadustele,"Kuigi erinevate uuringute tulemused kinnitavad ettevõtjate erilist tähelepanu töövõtjate isikuomadustele juba mitmel viimasel aastal , ei ole sellest järeldusi teinud noored ega koolid .",NaN,NaN,NaN,no,"The phrase 'isikuomadustele' denotes an object of focus rather than a place, so it is not an adverbial of place.",no,no,no,no,no,UNK

In [22]:
len(df1[df1["is_alive"]=="yes"])

892

In [23]:
len(df1[df1["is_time"]=="yes"])

356

In [24]:
len(df1[df1["is_event"]=="yes"])

227

In [25]:
len(df1[(df1["is_event"]=="yes") & (df1["is_time"]=="no")])

221