In [1]:
import sqlite3
import pandas as pd

In [23]:
elus = pd.read_csv("../data_files/elusolendid_srt_biol_elus.csv", sep=",", encoding="utf-8")
elus

        cnt          lemma
0     49116        inimene
1     23297           mees
2     11626           isik
3      8992          naine
4      6749           laps
...     ...            ...
2335     10    aselinnapea
2336     10        apostel
2337     10  antikangelane
2338     10  anestesioloog
2339     10     allhankija

[2340 rows x 2 columns]

In [27]:
elus2 = elus.drop(["cnt"], axis=1)
elus2

              lemma
0           inimene
1              mees
2              isik
3             naine
4              laps
...             ...
2335    aselinnapea
2336        apostel
2337  antikangelane
2338  anestesioloog
2339     allhankija

[2340 rows x 1 columns]

In [29]:
# uue andmebaasi loomine
con = sqlite3.connect("db_maarused.db")
cur = con.cursor()
cur.execute('pragma encoding=UTF8')

In [30]:
elus2.to_sql(name='elus_bio_v1', con=con)

2340

In [31]:
con.commit()

In [6]:
kohad = pd.read_csv("../data_files/loc_lemmas_edited.csv", sep=",", encoding="utf-8", header=None)
kohad = kohad.rename(columns={0: "lemma"})
kohad

               lemma
0               riik
1               küla
2               rand
3                maa
4           välismaa
...              ...
1060           tupik
1061       ummikseis
1062  liiklussegadus
1063     liikluskaos
1064  hallikassinine

[1065 rows x 1 columns]

In [8]:
kohad.to_sql(name='kohad_v1', con=con)

1065

In [9]:
con.commit()

In [10]:
con.close()